# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.request_options import RequestOptions
from .raw_client import AsyncRawApi, RawApi
from .types.active_session_response import ActiveSessionResponse
from .types.backup_environment_response import BackupEnvironmentResponse
from .types.cdp_url_response import CdpUrlResponse
from .types.close_environment_response import CloseEnvironmentResponse
from .types.create_sandbox_response import CreateSandboxResponse
from .types.create_snapshot_response import CreateSnapshotResponse
from .types.delete_sandbox_response import DeleteSandboxResponse
from .types.environment_state_response import EnvironmentStateResponse
from .types.evaluate_response import EvaluateResponse
from .types.heartbeat_response import HeartbeatResponse
from .types.job_status_response import JobStatusResponse
from .types.log_response import LogResponse
from .types.make_environment_response import MakeEnvironmentResponse
from .types.operation_event import OperationEvent
from .types.post_evaluation_result_response import PostEvaluationResultResponse
from .types.proxy_url_response import ProxyUrlResponse
from .types.reset_environment_response import ResetEnvironmentResponse
from .types.running_sessions_count_response import RunningSessionsCountResponse
from .types.setup_root_access_response import SetupRootAccessResponse
from .types.setup_sandbox_response import SetupSandboxResponse
from .types.sim_config_dataset import SimConfigDataset
from .types.simulator import Simulator
from .types.start_worker_response import StartWorkerResponse
from .types.test_cases_response import TestCasesResponse
from .types.worker_ready_response import WorkerReadyResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class Api:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : str
        The base url to use for requests from the client.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    client = Api(
        base_url="https://yourhost.com/path/to/api",
    )
    """

    def __init__(
        self,
        *,
        base_url: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=base_url,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._raw_client = RawApi(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> RawApi:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApi
        """
        return self._raw_client

    def make_environment(
        self,
        *,
        interface_type: str,
        env_id: str,
        interface_width: typing.Optional[int] = OMIT,
        interface_height: typing.Optional[int] = OMIT,
        source: typing.Optional[str] = OMIT,
        open_page_on_start: typing.Optional[bool] = OMIT,
        tag: typing.Optional[str] = OMIT,
        dataset: typing.Optional[str] = OMIT,
        artifact_id: typing.Optional[str] = OMIT,
        env_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        record_network_requests: typing.Optional[bool] = OMIT,
        record_actions: typing.Optional[bool] = OMIT,
        keepalive: typing.Optional[bool] = OMIT,
        alias: typing.Optional[str] = OMIT,
        fast: typing.Optional[bool] = OMIT,
        version: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakeEnvironmentResponse:
        """
        Parameters
        ----------
        interface_type : str

        env_id : str

        interface_width : typing.Optional[int]

        interface_height : typing.Optional[int]

        source : typing.Optional[str]

        open_page_on_start : typing.Optional[bool]

        tag : typing.Optional[str]

        dataset : typing.Optional[str]

        artifact_id : typing.Optional[str]

        env_config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        record_network_requests : typing.Optional[bool]

        record_actions : typing.Optional[bool]

        keepalive : typing.Optional[bool]

        alias : typing.Optional[str]

        fast : typing.Optional[bool]

        version : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakeEnvironmentResponse
            Environment created successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.make_environment(
            interface_type="interface_type",
            env_id="env_id",
        )
        """
        _response = self._raw_client.make_environment(
            interface_type=interface_type,
            env_id=env_id,
            interface_width=interface_width,
            interface_height=interface_height,
            source=source,
            open_page_on_start=open_page_on_start,
            tag=tag,
            dataset=dataset,
            artifact_id=artifact_id,
            env_config=env_config,
            record_network_requests=record_network_requests,
            record_actions=record_actions,
            keepalive=keepalive,
            alias=alias,
            fast=fast,
            version=version,
            request_options=request_options,
        )
        return _response.data

    def get_job_status(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobStatusResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobStatusResponse
            Job status retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_job_status(
            job_id="job_id",
        )
        """
        _response = self._raw_client.get_job_status(job_id, request_options=request_options)
        return _response.data

    def get_cdp_url(self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CdpUrlResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CdpUrlResponse
            CDP URL retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_cdp_url(
            job_id="job_id",
        )
        """
        _response = self._raw_client.get_cdp_url(job_id, request_options=request_options)
        return _response.data

    def get_proxy_url(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProxyUrlResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyUrlResponse
            Proxy URL retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_proxy_url(
            job_id="job_id",
        )
        """
        _response = self._raw_client.get_proxy_url(job_id, request_options=request_options)
        return _response.data

    def close_environment(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CloseEnvironmentResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CloseEnvironmentResponse
            Environment closed successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.close_environment(
            job_id="job_id",
        )
        """
        _response = self._raw_client.close_environment(job_id, request_options=request_options)
        return _response.data

    def backup_environment(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BackupEnvironmentResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BackupEnvironmentResponse
            Environment backed up successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.backup_environment(
            job_id="job_id",
        )
        """
        _response = self._raw_client.backup_environment(job_id, request_options=request_options)
        return _response.data

    def reset_environment(
        self,
        job_id: str,
        *,
        test_case_public_id: typing.Optional[str] = OMIT,
        agent_version: typing.Optional[str] = OMIT,
        load_browser_state: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResetEnvironmentResponse:
        """
        Parameters
        ----------
        job_id : str

        test_case_public_id : typing.Optional[str]

        agent_version : typing.Optional[str]

        load_browser_state : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResetEnvironmentResponse
            Environment reset successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.reset_environment(
            job_id="job_id",
        )
        """
        _response = self._raw_client.reset_environment(
            job_id,
            test_case_public_id=test_case_public_id,
            agent_version=agent_version,
            load_browser_state=load_browser_state,
            request_options=request_options,
        )
        return _response.data

    def get_environment_state(
        self,
        job_id: str,
        *,
        merge_mutations: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentStateResponse:
        """
        Parameters
        ----------
        job_id : str

        merge_mutations : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentStateResponse
            Environment state retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_environment_state(
            job_id="job_id",
            merge_mutations=True,
        )
        """
        _response = self._raw_client.get_environment_state(
            job_id, merge_mutations=merge_mutations, request_options=request_options
        )
        return _response.data

    def get_worker_ready(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkerReadyResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkerReadyResponse
            Worker ready status retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_worker_ready(
            job_id="job_id",
        )
        """
        _response = self._raw_client.get_worker_ready(job_id, request_options=request_options)
        return _response.data

    def send_heartbeat(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HeartbeatResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HeartbeatResponse
            Heartbeat sent successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.send_heartbeat(
            job_id="job_id",
        )
        """
        _response = self._raw_client.send_heartbeat(job_id, request_options=request_options)
        return _response.data

    def get_active_session(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ActiveSessionResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActiveSessionResponse
            Active session retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_active_session(
            job_id="job_id",
        )
        """
        _response = self._raw_client.get_active_session(job_id, request_options=request_options)
        return _response.data

    def evaluate_session(
        self,
        session_id: str,
        *,
        value: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluateResponse:
        """
        Parameters
        ----------
        session_id : str

        value : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluateResponse
            Evaluation completed successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.evaluate_session(
            session_id="session_id",
        )
        """
        _response = self._raw_client.evaluate_session(session_id, value=value, request_options=request_options)
        return _response.data

    def post_evaluation_result(
        self,
        session_id: str,
        *,
        success: bool,
        reason: typing.Optional[str] = OMIT,
        agent_version: typing.Optional[str] = OMIT,
        mutations: typing.Optional[typing.Sequence[typing.Dict[str, typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationResultResponse:
        """
        Parameters
        ----------
        session_id : str

        success : bool

        reason : typing.Optional[str]

        agent_version : typing.Optional[str]

        mutations : typing.Optional[typing.Sequence[typing.Dict[str, typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationResultResponse
            Evaluation result posted successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.post_evaluation_result(
            session_id="session_id",
            success=True,
        )
        """
        _response = self._raw_client.post_evaluation_result(
            session_id,
            success=success,
            reason=reason,
            agent_version=agent_version,
            mutations=mutations,
            request_options=request_options,
        )
        return _response.data

    def log_message(
        self,
        session_id: str,
        *,
        source: str,
        type: str,
        message: typing.Dict[str, typing.Optional[typing.Any]],
        timestamp: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LogResponse:
        """
        Parameters
        ----------
        session_id : str

        source : str

        type : str

        message : typing.Dict[str, typing.Optional[typing.Any]]

        timestamp : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LogResponse
            Log message sent successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.log_message(
            session_id="session_id",
            source="source",
            type="type",
            message={"key": "value"},
            timestamp="timestamp",
        )
        """
        _response = self._raw_client.log_message(
            session_id, source=source, type=type, message=message, timestamp=timestamp, request_options=request_options
        )
        return _response.data

    def list_simulators(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[Simulator]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Simulator]
            Simulators retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.list_simulators()
        """
        _response = self._raw_client.list_simulators(request_options=request_options)
        return _response.data

    def get_test_cases(
        self,
        *,
        simulator_name: typing.Optional[str] = None,
        simulator_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestCasesResponse:
        """
        Parameters
        ----------
        simulator_name : typing.Optional[str]

        simulator_id : typing.Optional[str]

        page_size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestCasesResponse
            Test cases retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_test_cases(
            simulator_name="simulator_name",
            simulator_id="simulator_id",
            page_size=1,
        )
        """
        _response = self._raw_client.get_test_cases(
            simulator_name=simulator_name,
            simulator_id=simulator_id,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    def get_running_sessions_count(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RunningSessionsCountResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RunningSessionsCountResponse
            Running sessions count retrieved successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.get_running_sessions_count()
        """
        _response = self._raw_client.get_running_sessions_count(request_options=request_options)
        return _response.data

    def monitor_operation(
        self, correlation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[OperationEvent]:
        """
        Monitor the progress of long-running operations (sandbox creation, setup, etc.) via SSE.

        **Event Flow:**
        1. First event: `type: "connected"` - Connection established, continue listening
        2. Progress events: `type: "progress"` with `message` field - Operation updates
        3. Completion: `type: "run_result"` or `"ssh_result"` - Operation finished
           - Check `success: true` for successful completion
           - Check `error` or `message` field if `success: false`
        4. Error: `type: "error"` - Operation failed, check `error` or `message` field

        **Data Format:**
        SSE data is base64-encoded JSON. Decode it to get the OperationEvent object.

        **Client Implementation Required:**
        - Decode base64 data from each SSE event
        - Parse JSON to OperationEvent
        - Check event.type and event.success to determine operation status
        - Continue listening until receiving a terminal event (run_result, ssh_result, or error)
        - Return success/error based on the terminal event

        **Example (pseudo-code):**
        ```
        for event in stream:
          decoded = base64_decode(event.data)
          operation_event = json_parse(decoded)

          if operation_event.type == "connected":
            continue  # Keep listening
          elif operation_event.type in ["run_result", "ssh_result"]:
            if operation_event.success:
              return SUCCESS
            else:
              return ERROR(operation_event.error || operation_event.message)
          elif operation_event.type == "error":
            return ERROR(operation_event.error || operation_event.message)
        ```

        Parameters
        ----------
        correlation_id : str
            Correlation ID from sandbox creation or setup operation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[OperationEvent]
            SSE stream of operation events

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        response = client.monitor_operation(
            correlation_id="correlation_id",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.monitor_operation(correlation_id, request_options=request_options) as r:
            yield from r.data

    def create_sandbox(
        self,
        *,
        dataset: str,
        plato_dataset_config: SimConfigDataset,
        timeout: typing.Optional[int] = OMIT,
        wait_time: typing.Optional[int] = OMIT,
        alias: typing.Optional[str] = OMIT,
        artifact_id: typing.Optional[str] = OMIT,
        service: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSandboxResponse:
        """
        Parameters
        ----------
        dataset : str
            Dataset name (e.g., "base")

        plato_dataset_config : SimConfigDataset

        timeout : typing.Optional[int]
            Timeout in seconds for sandbox creation

        wait_time : typing.Optional[int]
            Wait time in seconds

        alias : typing.Optional[str]
            Human-readable alias for the sandbox

        artifact_id : typing.Optional[str]
            Optional artifact ID to create sandbox from snapshot

        service : typing.Optional[str]
            Service name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSandboxResponse
            Sandbox creation initiated successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.create_sandbox(
            dataset="dataset",
            plato_dataset_config=SimConfigDataset(
                compute=SimConfigCompute(
                    cpus=1,
                    memory=1,
                    disk=1,
                    app_port=1,
                    plato_messaging_port=1,
                ),
                metadata=SimConfigMetadata(
                    name="name",
                ),
            ),
        )
        """
        _response = self._raw_client.create_sandbox(
            dataset=dataset,
            plato_dataset_config=plato_dataset_config,
            timeout=timeout,
            wait_time=wait_time,
            alias=alias,
            artifact_id=artifact_id,
            service=service,
            request_options=request_options,
        )
        return _response.data

    def setup_sandbox(
        self,
        job_id: str,
        *,
        dataset: str,
        plato_dataset_config: SimConfigDataset,
        ssh_public_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SetupSandboxResponse:
        """
        Parameters
        ----------
        job_id : str

        dataset : str
            Dataset name

        plato_dataset_config : SimConfigDataset

        ssh_public_key : typing.Optional[str]
            SSH public key to install for plato user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetupSandboxResponse
            Sandbox setup initiated successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.setup_sandbox(
            job_id="job_id",
            dataset="dataset",
            plato_dataset_config=SimConfigDataset(
                compute=SimConfigCompute(
                    cpus=1,
                    memory=1,
                    disk=1,
                    app_port=1,
                    plato_messaging_port=1,
                ),
                metadata=SimConfigMetadata(
                    name="name",
                ),
            ),
        )
        """
        _response = self._raw_client.setup_sandbox(
            job_id,
            dataset=dataset,
            plato_dataset_config=plato_dataset_config,
            ssh_public_key=ssh_public_key,
            request_options=request_options,
        )
        return _response.data

    def delete_sandbox(
        self, public_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteSandboxResponse:
        """
        Parameters
        ----------
        public_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteSandboxResponse
            Sandbox deleted successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.delete_sandbox(
            public_id="public_id",
        )
        """
        _response = self._raw_client.delete_sandbox(public_id, request_options=request_options)
        return _response.data

    def create_snapshot(
        self,
        public_id: str,
        *,
        service: typing.Optional[str] = OMIT,
        git_hash: typing.Optional[str] = OMIT,
        dataset: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSnapshotResponse:
        """
        Parameters
        ----------
        public_id : str

        service : typing.Optional[str]

        git_hash : typing.Optional[str]

        dataset : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSnapshotResponse
            Snapshot created successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.create_snapshot(
            public_id="public_id",
        )
        """
        _response = self._raw_client.create_snapshot(
            public_id, service=service, git_hash=git_hash, dataset=dataset, request_options=request_options
        )
        return _response.data

    def start_worker(
        self,
        public_id: str,
        *,
        dataset: str,
        plato_dataset_config: SimConfigDataset,
        service: typing.Optional[str] = OMIT,
        timeout: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkerResponse:
        """
        Parameters
        ----------
        public_id : str

        dataset : str

        plato_dataset_config : SimConfigDataset

        service : typing.Optional[str]

        timeout : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkerResponse
            Worker started successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.start_worker(
            public_id="public_id",
            dataset="dataset",
            plato_dataset_config=SimConfigDataset(
                compute=SimConfigCompute(
                    cpus=1,
                    memory=1,
                    disk=1,
                    app_port=1,
                    plato_messaging_port=1,
                ),
                metadata=SimConfigMetadata(
                    name="name",
                ),
            ),
        )
        """
        _response = self._raw_client.start_worker(
            public_id,
            dataset=dataset,
            plato_dataset_config=plato_dataset_config,
            service=service,
            timeout=timeout,
            request_options=request_options,
        )
        return _response.data

    def setup_root_access(
        self,
        public_id: str,
        *,
        ssh_public_key: str,
        timeout: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SetupRootAccessResponse:
        """
        Parameters
        ----------
        public_id : str

        ssh_public_key : str
            SSH public key to install for root user

        timeout : typing.Optional[int]
            Timeout in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetupRootAccessResponse
            Root access setup successfully

        Examples
        --------
        client = Api(
            base_url="https://yourhost.com/path/to/api",
        )
        client.setup_root_access(
            public_id="public_id",
            ssh_public_key="ssh_public_key",
        )
        """
        _response = self._raw_client.setup_root_access(
            public_id, ssh_public_key=ssh_public_key, timeout=timeout, request_options=request_options
        )
        return _response.data


class AsyncApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : str
        The base url to use for requests from the client.

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    client = AsyncApi(
        base_url="https://yourhost.com/path/to/api",
    )
    """

    def __init__(
        self,
        *,
        base_url: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=base_url,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._raw_client = AsyncRawApi(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApi:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApi
        """
        return self._raw_client

    async def make_environment(
        self,
        *,
        interface_type: str,
        env_id: str,
        interface_width: typing.Optional[int] = OMIT,
        interface_height: typing.Optional[int] = OMIT,
        source: typing.Optional[str] = OMIT,
        open_page_on_start: typing.Optional[bool] = OMIT,
        tag: typing.Optional[str] = OMIT,
        dataset: typing.Optional[str] = OMIT,
        artifact_id: typing.Optional[str] = OMIT,
        env_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        record_network_requests: typing.Optional[bool] = OMIT,
        record_actions: typing.Optional[bool] = OMIT,
        keepalive: typing.Optional[bool] = OMIT,
        alias: typing.Optional[str] = OMIT,
        fast: typing.Optional[bool] = OMIT,
        version: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakeEnvironmentResponse:
        """
        Parameters
        ----------
        interface_type : str

        env_id : str

        interface_width : typing.Optional[int]

        interface_height : typing.Optional[int]

        source : typing.Optional[str]

        open_page_on_start : typing.Optional[bool]

        tag : typing.Optional[str]

        dataset : typing.Optional[str]

        artifact_id : typing.Optional[str]

        env_config : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        record_network_requests : typing.Optional[bool]

        record_actions : typing.Optional[bool]

        keepalive : typing.Optional[bool]

        alias : typing.Optional[str]

        fast : typing.Optional[bool]

        version : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakeEnvironmentResponse
            Environment created successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.make_environment(
                interface_type="interface_type",
                env_id="env_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.make_environment(
            interface_type=interface_type,
            env_id=env_id,
            interface_width=interface_width,
            interface_height=interface_height,
            source=source,
            open_page_on_start=open_page_on_start,
            tag=tag,
            dataset=dataset,
            artifact_id=artifact_id,
            env_config=env_config,
            record_network_requests=record_network_requests,
            record_actions=record_actions,
            keepalive=keepalive,
            alias=alias,
            fast=fast,
            version=version,
            request_options=request_options,
        )
        return _response.data

    async def get_job_status(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobStatusResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobStatusResponse
            Job status retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_job_status(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_status(job_id, request_options=request_options)
        return _response.data

    async def get_cdp_url(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CdpUrlResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CdpUrlResponse
            CDP URL retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_cdp_url(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_cdp_url(job_id, request_options=request_options)
        return _response.data

    async def get_proxy_url(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProxyUrlResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProxyUrlResponse
            Proxy URL retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_proxy_url(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_proxy_url(job_id, request_options=request_options)
        return _response.data

    async def close_environment(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CloseEnvironmentResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CloseEnvironmentResponse
            Environment closed successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.close_environment(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.close_environment(job_id, request_options=request_options)
        return _response.data

    async def backup_environment(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BackupEnvironmentResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BackupEnvironmentResponse
            Environment backed up successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.backup_environment(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.backup_environment(job_id, request_options=request_options)
        return _response.data

    async def reset_environment(
        self,
        job_id: str,
        *,
        test_case_public_id: typing.Optional[str] = OMIT,
        agent_version: typing.Optional[str] = OMIT,
        load_browser_state: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResetEnvironmentResponse:
        """
        Parameters
        ----------
        job_id : str

        test_case_public_id : typing.Optional[str]

        agent_version : typing.Optional[str]

        load_browser_state : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResetEnvironmentResponse
            Environment reset successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.reset_environment(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.reset_environment(
            job_id,
            test_case_public_id=test_case_public_id,
            agent_version=agent_version,
            load_browser_state=load_browser_state,
            request_options=request_options,
        )
        return _response.data

    async def get_environment_state(
        self,
        job_id: str,
        *,
        merge_mutations: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentStateResponse:
        """
        Parameters
        ----------
        job_id : str

        merge_mutations : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentStateResponse
            Environment state retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_environment_state(
                job_id="job_id",
                merge_mutations=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_environment_state(
            job_id, merge_mutations=merge_mutations, request_options=request_options
        )
        return _response.data

    async def get_worker_ready(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkerReadyResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkerReadyResponse
            Worker ready status retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_worker_ready(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_worker_ready(job_id, request_options=request_options)
        return _response.data

    async def send_heartbeat(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HeartbeatResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HeartbeatResponse
            Heartbeat sent successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.send_heartbeat(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_heartbeat(job_id, request_options=request_options)
        return _response.data

    async def get_active_session(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ActiveSessionResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActiveSessionResponse
            Active session retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_active_session(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_active_session(job_id, request_options=request_options)
        return _response.data

    async def evaluate_session(
        self,
        session_id: str,
        *,
        value: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvaluateResponse:
        """
        Parameters
        ----------
        session_id : str

        value : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvaluateResponse
            Evaluation completed successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.evaluate_session(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.evaluate_session(session_id, value=value, request_options=request_options)
        return _response.data

    async def post_evaluation_result(
        self,
        session_id: str,
        *,
        success: bool,
        reason: typing.Optional[str] = OMIT,
        agent_version: typing.Optional[str] = OMIT,
        mutations: typing.Optional[typing.Sequence[typing.Dict[str, typing.Optional[typing.Any]]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostEvaluationResultResponse:
        """
        Parameters
        ----------
        session_id : str

        success : bool

        reason : typing.Optional[str]

        agent_version : typing.Optional[str]

        mutations : typing.Optional[typing.Sequence[typing.Dict[str, typing.Optional[typing.Any]]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostEvaluationResultResponse
            Evaluation result posted successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.post_evaluation_result(
                session_id="session_id",
                success=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_evaluation_result(
            session_id,
            success=success,
            reason=reason,
            agent_version=agent_version,
            mutations=mutations,
            request_options=request_options,
        )
        return _response.data

    async def log_message(
        self,
        session_id: str,
        *,
        source: str,
        type: str,
        message: typing.Dict[str, typing.Optional[typing.Any]],
        timestamp: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LogResponse:
        """
        Parameters
        ----------
        session_id : str

        source : str

        type : str

        message : typing.Dict[str, typing.Optional[typing.Any]]

        timestamp : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LogResponse
            Log message sent successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.log_message(
                session_id="session_id",
                source="source",
                type="type",
                message={"key": "value"},
                timestamp="timestamp",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.log_message(
            session_id, source=source, type=type, message=message, timestamp=timestamp, request_options=request_options
        )
        return _response.data

    async def list_simulators(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[Simulator]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[Simulator]
            Simulators retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.list_simulators()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_simulators(request_options=request_options)
        return _response.data

    async def get_test_cases(
        self,
        *,
        simulator_name: typing.Optional[str] = None,
        simulator_id: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TestCasesResponse:
        """
        Parameters
        ----------
        simulator_name : typing.Optional[str]

        simulator_id : typing.Optional[str]

        page_size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TestCasesResponse
            Test cases retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_test_cases(
                simulator_name="simulator_name",
                simulator_id="simulator_id",
                page_size=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_test_cases(
            simulator_name=simulator_name,
            simulator_id=simulator_id,
            page_size=page_size,
            request_options=request_options,
        )
        return _response.data

    async def get_running_sessions_count(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RunningSessionsCountResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RunningSessionsCountResponse
            Running sessions count retrieved successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.get_running_sessions_count()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_running_sessions_count(request_options=request_options)
        return _response.data

    async def monitor_operation(
        self, correlation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[OperationEvent]:
        """
        Monitor the progress of long-running operations (sandbox creation, setup, etc.) via SSE.

        **Event Flow:**
        1. First event: `type: "connected"` - Connection established, continue listening
        2. Progress events: `type: "progress"` with `message` field - Operation updates
        3. Completion: `type: "run_result"` or `"ssh_result"` - Operation finished
           - Check `success: true` for successful completion
           - Check `error` or `message` field if `success: false`
        4. Error: `type: "error"` - Operation failed, check `error` or `message` field

        **Data Format:**
        SSE data is base64-encoded JSON. Decode it to get the OperationEvent object.

        **Client Implementation Required:**
        - Decode base64 data from each SSE event
        - Parse JSON to OperationEvent
        - Check event.type and event.success to determine operation status
        - Continue listening until receiving a terminal event (run_result, ssh_result, or error)
        - Return success/error based on the terminal event

        **Example (pseudo-code):**
        ```
        for event in stream:
          decoded = base64_decode(event.data)
          operation_event = json_parse(decoded)

          if operation_event.type == "connected":
            continue  # Keep listening
          elif operation_event.type in ["run_result", "ssh_result"]:
            if operation_event.success:
              return SUCCESS
            else:
              return ERROR(operation_event.error || operation_event.message)
          elif operation_event.type == "error":
            return ERROR(operation_event.error || operation_event.message)
        ```

        Parameters
        ----------
        correlation_id : str
            Correlation ID from sandbox creation or setup operation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[OperationEvent]
            SSE stream of operation events

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            response = await client.monitor_operation(
                correlation_id="correlation_id",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.monitor_operation(correlation_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def create_sandbox(
        self,
        *,
        dataset: str,
        plato_dataset_config: SimConfigDataset,
        timeout: typing.Optional[int] = OMIT,
        wait_time: typing.Optional[int] = OMIT,
        alias: typing.Optional[str] = OMIT,
        artifact_id: typing.Optional[str] = OMIT,
        service: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSandboxResponse:
        """
        Parameters
        ----------
        dataset : str
            Dataset name (e.g., "base")

        plato_dataset_config : SimConfigDataset

        timeout : typing.Optional[int]
            Timeout in seconds for sandbox creation

        wait_time : typing.Optional[int]
            Wait time in seconds

        alias : typing.Optional[str]
            Human-readable alias for the sandbox

        artifact_id : typing.Optional[str]
            Optional artifact ID to create sandbox from snapshot

        service : typing.Optional[str]
            Service name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSandboxResponse
            Sandbox creation initiated successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.create_sandbox(
                dataset="dataset",
                plato_dataset_config=SimConfigDataset(
                    compute=SimConfigCompute(
                        cpus=1,
                        memory=1,
                        disk=1,
                        app_port=1,
                        plato_messaging_port=1,
                    ),
                    metadata=SimConfigMetadata(
                        name="name",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_sandbox(
            dataset=dataset,
            plato_dataset_config=plato_dataset_config,
            timeout=timeout,
            wait_time=wait_time,
            alias=alias,
            artifact_id=artifact_id,
            service=service,
            request_options=request_options,
        )
        return _response.data

    async def setup_sandbox(
        self,
        job_id: str,
        *,
        dataset: str,
        plato_dataset_config: SimConfigDataset,
        ssh_public_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SetupSandboxResponse:
        """
        Parameters
        ----------
        job_id : str

        dataset : str
            Dataset name

        plato_dataset_config : SimConfigDataset

        ssh_public_key : typing.Optional[str]
            SSH public key to install for plato user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetupSandboxResponse
            Sandbox setup initiated successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.setup_sandbox(
                job_id="job_id",
                dataset="dataset",
                plato_dataset_config=SimConfigDataset(
                    compute=SimConfigCompute(
                        cpus=1,
                        memory=1,
                        disk=1,
                        app_port=1,
                        plato_messaging_port=1,
                    ),
                    metadata=SimConfigMetadata(
                        name="name",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.setup_sandbox(
            job_id,
            dataset=dataset,
            plato_dataset_config=plato_dataset_config,
            ssh_public_key=ssh_public_key,
            request_options=request_options,
        )
        return _response.data

    async def delete_sandbox(
        self, public_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteSandboxResponse:
        """
        Parameters
        ----------
        public_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteSandboxResponse
            Sandbox deleted successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.delete_sandbox(
                public_id="public_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_sandbox(public_id, request_options=request_options)
        return _response.data

    async def create_snapshot(
        self,
        public_id: str,
        *,
        service: typing.Optional[str] = OMIT,
        git_hash: typing.Optional[str] = OMIT,
        dataset: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSnapshotResponse:
        """
        Parameters
        ----------
        public_id : str

        service : typing.Optional[str]

        git_hash : typing.Optional[str]

        dataset : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSnapshotResponse
            Snapshot created successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.create_snapshot(
                public_id="public_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_snapshot(
            public_id, service=service, git_hash=git_hash, dataset=dataset, request_options=request_options
        )
        return _response.data

    async def start_worker(
        self,
        public_id: str,
        *,
        dataset: str,
        plato_dataset_config: SimConfigDataset,
        service: typing.Optional[str] = OMIT,
        timeout: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartWorkerResponse:
        """
        Parameters
        ----------
        public_id : str

        dataset : str

        plato_dataset_config : SimConfigDataset

        service : typing.Optional[str]

        timeout : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartWorkerResponse
            Worker started successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.start_worker(
                public_id="public_id",
                dataset="dataset",
                plato_dataset_config=SimConfigDataset(
                    compute=SimConfigCompute(
                        cpus=1,
                        memory=1,
                        disk=1,
                        app_port=1,
                        plato_messaging_port=1,
                    ),
                    metadata=SimConfigMetadata(
                        name="name",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_worker(
            public_id,
            dataset=dataset,
            plato_dataset_config=plato_dataset_config,
            service=service,
            timeout=timeout,
            request_options=request_options,
        )
        return _response.data

    async def setup_root_access(
        self,
        public_id: str,
        *,
        ssh_public_key: str,
        timeout: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SetupRootAccessResponse:
        """
        Parameters
        ----------
        public_id : str

        ssh_public_key : str
            SSH public key to install for root user

        timeout : typing.Optional[int]
            Timeout in seconds

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SetupRootAccessResponse
            Root access setup successfully

        Examples
        --------
        import asyncio

        client = AsyncApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.setup_root_access(
                public_id="public_id",
                ssh_public_key="ssh_public_key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.setup_root_access(
            public_id, ssh_public_key=ssh_public_key, timeout=timeout, request_options=request_options
        )
        return _response.data
