// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../../../../index.js";

/**
 * @example
 *     {
 *         dataset: "dataset",
 *         plato_dataset_config: {
 *             compute: {},
 *             metadata: {}
 *         }
 *     }
 */
export interface SetupSandboxRequest {
    /** Service name */
    service?: string;
    /** Dataset name */
    dataset: string;
    /** Dataset config for templating */
    plato_dataset_config: Api.SimConfigDataset;
    /** Request timeout in seconds */
    request_timeout?: number;
    /** SSH password for plato user (optional) */
    ssh_password?: string;
    /** SSH public key to add to plato user's authorized_keys (optional) */
    ssh_public_key?: string;
}
