// This file was auto-generated by Fern from our API Definition.

import { Env } from "./api/resources/env/client/Client.js";
import { Gitea } from "./api/resources/gitea/client/Client.js";
import { PublicBuild } from "./api/resources/publicBuild/client/Client.js";
import { Simulator } from "./api/resources/simulator/client/Client.js";
import { Testcases } from "./api/resources/testcases/client/Client.js";
import { User } from "./api/resources/user/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace ApiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ApiClient {
    protected readonly _options: ApiClient.Options;
    protected _env: Env | undefined;
    protected _gitea: Gitea | undefined;
    protected _publicBuild: PublicBuild | undefined;
    protected _simulator: Simulator | undefined;
    protected _testcases: Testcases | undefined;
    protected _user: User | undefined;

    constructor(_options: ApiClient.Options) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get env(): Env {
        return (this._env ??= new Env(this._options));
    }

    public get gitea(): Gitea {
        return (this._gitea ??= new Gitea(this._options));
    }

    public get publicBuild(): PublicBuild {
        return (this._publicBuild ??= new PublicBuild(this._options));
    }

    public get simulator(): Simulator {
        return (this._simulator ??= new Simulator(this._options));
    }

    public get testcases(): Testcases {
        return (this._testcases ??= new Testcases(this._options));
    }

    public get user(): User {
        return (this._user ??= new User(this._options));
    }
}
