// This file was auto-generated by Fern from our API Definition.

export interface EvaluateResponse {
    score?: EvaluateResponse.Score;
}

export namespace EvaluateResponse {
    export interface Score {
        result?: Score.Result;
    }

    export namespace Score {
        export interface Result {
            correct?: boolean;
            reason?: string;
            diffs?: Record<string, unknown>[];
            expected_mutations?: Record<string, unknown>[];
            mutations?: Record<string, unknown>[];
        }
    }
}
