// This file was auto-generated by Fern from our API Definition.

export interface EvaluationResult {
    success: boolean;
    reason?: string;
    diffs?: Record<string, unknown>[];
    expected_mutations?: Record<string, unknown>[];
    actual_mutations?: Record<string, unknown>[];
}
