// This file was auto-generated by Fern from our API Definition.

export interface PlatoTaskMetadata {
    reasoning_level?: PlatoTaskMetadata.ReasoningLevel;
    skills?: string[];
    capabilities?: string[];
    tags?: string[];
    rejected?: boolean;
}

export namespace PlatoTaskMetadata {
    export const ReasoningLevel = {
        Level1: "level_1",
        Level2: "level_2",
        Level3: "level_3",
        Level4: "level_4",
        Level5: "level_5",
    } as const;
    export type ReasoningLevel = (typeof ReasoningLevel)[keyof typeof ReasoningLevel];
}
