// This file was auto-generated by Fern from our API Definition.

export interface ResetEnvironmentResponse {
    success: boolean;
    error?: string;
    data?: ResetEnvironmentResponse.Data;
}

export namespace ResetEnvironmentResponse {
    export interface Data {
        run_session_id?: string;
    }
}
