// This file was auto-generated by Fern from our API Definition.

export interface SimConfigCompute {
    cpus: number;
    memory: number;
    disk: number;
    app_port: number;
    plato_messaging_port: number;
}
