// This file was auto-generated by Fern from our API Definition.

export interface SimConfigService {
    type: string;
    file?: string;
    required_healthy_containers?: string[];
    healthy_wait_timeout?: number;
}
