// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../index.js";

export interface TestCase {
    publicId: string;
    name: string;
    prompt: string;
    startUrl: string;
    simulator: TestCase.Simulator;
    averageTimeTaken?: number;
    averageStepsTaken?: number;
    defaultScoringConfig?: TestCase.DefaultScoringConfig;
    scoringTypes?: TestCase.ScoringTypes.Item[];
    outputSchema?: Record<string, unknown>;
    isSample?: boolean;
    simulatorArtifactId?: string;
    metadataConfig?: Api.TaskMetadata;
}

export namespace TestCase {
    export interface Simulator {
        name?: string;
        id?: number;
    }

    export interface DefaultScoringConfig {
        num_sessions_used?: number;
    }

    export type ScoringTypes = ScoringTypes.Item[];

    export namespace ScoringTypes {
        export const Item = {
            Output: "output",
            Mutations: "mutations",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
