// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../index.js";

export interface TestCasesResponse {
    testcases: Api.TestCase[];
    total?: number;
    page?: number;
    page_size?: number;
}
