// This file was auto-generated by Fern from our API Definition.

export interface WorkerReadyResponse {
    ready: boolean;
    worker_ip?: string;
    worker_port?: number;
    health_status?: Record<string, unknown>;
    error?: string;
}
