// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../../../../index.js";

/**
 * @example
 *     {
 *         authorization: "authorization",
 *         "X-Internal-Service": "X-Internal-Service",
 *         name: "name",
 *         config: {
 *             type: "proxy"
 *         },
 *         simType: "simType"
 *     }
 */
export interface CreateSimulatorRequest {
    authorization?: string;
    "X-Internal-Service"?: string;
    name: string;
    url?: string;
    description?: string;
    imgUrl?: string;
    config: Api.SimulatorConfig;
    ancestors?: string[];
    enabled?: boolean;
    simType: string;
    jobName?: string;
    internalAppPort?: number;
    supportedProviders?: string[];
}
