// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../../../../index.js";

/**
 * @example
 *     {
 *         authorization: "authorization",
 *         "X-Internal-Service": "X-Internal-Service",
 *         body: {}
 *     }
 */
export interface EvaluateSessionApiEnvSessionSessionIdEvaluatePostRequest {
    authorization?: string;
    "X-Internal-Service"?: string;
    body?: Api.EvaluateRequest;
}
