// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         authorization: "authorization",
 *         "X-Internal-Service": "X-Internal-Service"
 *     }
 */
export interface GetProxyUrlApiEnvJobGroupIdProxyUrlGetRequest {
    authorization?: string;
    "X-Internal-Service"?: string;
}
