// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         authorization: "authorization",
 *         "X-Internal-Service": "X-Internal-Service",
 *         interface_type: "browser",
 *         source: "source",
 *         env_id: "env_id",
 *         env_config: {
 *             "key": "value"
 *         }
 *     }
 */
export interface MakeEnvRequest2 {
    authorization?: string;
    "X-Internal-Service"?: string;
    interface_type: MakeEnvRequest2.InterfaceType;
    interface_width?: number;
    interface_height?: number;
    source: string;
    open_page_on_start?: boolean;
    env_id: string;
    env_config: Record<string, unknown>;
    record_network_requests?: boolean;
    record_actions?: boolean;
    load_chrome_extensions?: string[];
    keepalive?: boolean;
    alias?: string;
    fast?: boolean;
    version?: string;
    tag?: string;
    dataset?: string;
    artifact_id?: string;
    timeout?: number;
}

export namespace MakeEnvRequest2 {
    export const InterfaceType = {
        Browser: "browser",
        Computer: "computer",
        Noop: "noop",
    } as const;
    export type InterfaceType = (typeof InterfaceType)[keyof typeof InterfaceType];
}
