// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../../../../index.js";

/**
 * @example
 *     {
 *         authorization: "authorization",
 *         "X-Internal-Service": "X-Internal-Service"
 *     }
 */
export interface ResetEnvRequest {
    authorization?: string;
    "X-Internal-Service"?: string;
    task?: Api.ResetEnvTask;
    agent_version?: string;
    model?: string;
    source?: string;
    load_browser_state?: boolean;
    viewport_width?: number;
    viewport_height?: number;
    test_case_public_id?: string;
    replayed_from_session_id?: string;
    user_id?: number;
}
