// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         authorization: "authorization",
 *         "X-Internal-Service": "X-Internal-Service",
 *         success: true
 *     }
 */
export interface ScoreRequest {
    authorization?: string;
    "X-Internal-Service"?: string;
    success: boolean;
    reason?: string;
    agent_version?: string;
    mutations?: Record<string, unknown>[];
}
