/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSimulatorRequest,
  EvaluateRequest,
  HTTPValidationError,
  JobStatusResponse,
  Log,
  MakeEnvRequest2,
  MakeEnvResponse,
  ResetEnvRequest,
  ScoreRequest,
  WorkerReadyResponse,
} from '../models/index';
import {
    CreateSimulatorRequestFromJSON,
    CreateSimulatorRequestToJSON,
    EvaluateRequestFromJSON,
    EvaluateRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    JobStatusResponseFromJSON,
    JobStatusResponseToJSON,
    LogFromJSON,
    LogToJSON,
    MakeEnvRequest2FromJSON,
    MakeEnvRequest2ToJSON,
    MakeEnvResponseFromJSON,
    MakeEnvResponseToJSON,
    ResetEnvRequestFromJSON,
    ResetEnvRequestToJSON,
    ScoreRequestFromJSON,
    ScoreRequestToJSON,
    WorkerReadyResponseFromJSON,
    WorkerReadyResponseToJSON,
} from '../models/index';

export interface BackupEnvApiEnvJobGroupIdBackupPostRequest {
    jobGroupId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface CloseEnvApiEnvJobGroupIdClosePostRequest {
    jobGroupId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface CreateSimulatorApiEnvSimulatorsPostRequest {
    createSimulatorRequest: CreateSimulatorRequest;
    authorization?: string;
    xInternalService?: string;
}

export interface EvaluateSessionApiEnvSessionSessionIdEvaluatePostRequest {
    sessionId: string;
    authorization?: string;
    xInternalService?: string;
    evaluateRequest?: EvaluateRequest;
}

export interface GetActiveSessionApiEnvJobGroupIdActiveSessionGetRequest {
    jobGroupId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface GetCdpUrlApiEnvJobGroupIdCdpUrlGetRequest {
    jobGroupId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface GetEnvStateApiEnvJobGroupIdStateGetRequest {
    jobGroupId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface GetJobStatusApiEnvJobGroupIdStatusGetRequest {
    jobGroupId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface GetProxyUrlApiEnvJobGroupIdProxyUrlGetRequest {
    jobGroupId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface GetSimulatorsApiEnvSimulatorsGetRequest {
    authorization?: string;
    xInternalService?: string;
}

export interface GetWorkerReadyApiEnvJobIdWorkerReadyGetRequest {
    jobId: string;
    timeout?: number;
    authorization?: string;
    xInternalService?: string;
}

export interface LogStateMutationApiEnvSessionIdLogPostRequest {
    sessionId: string;
    log: Log;
}

export interface MakeEnvApiEnvMake2PostRequest {
    makeEnvRequest2: MakeEnvRequest2;
    authorization?: string;
    xInternalService?: string;
}

export interface ResetEnvApiEnvJobGroupIdResetPostRequest {
    jobGroupId: string;
    resetEnvRequest: ResetEnvRequest;
    authorization?: string;
    xInternalService?: string;
}

export interface ScoreEnvApiEnvSessionSessionIdScorePostRequest {
    sessionId: string;
    scoreRequest: ScoreRequest;
    authorization?: string;
    xInternalService?: string;
}

export interface SendHeartbeatApiEnvJobIdHeartbeatPostRequest {
    jobId: string;
    authorization?: string;
    xInternalService?: string;
}

/**
 * 
 */
export class EnvApi extends runtime.BaseAPI {

    /**
     * Create a backup of the environment.
     * Backup Env
     */
    async backupEnvApiEnvJobGroupIdBackupPostRaw(requestParameters: BackupEnvApiEnvJobGroupIdBackupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling backupEnvApiEnvJobGroupIdBackupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/backup`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a backup of the environment.
     * Backup Env
     */
    async backupEnvApiEnvJobGroupIdBackupPost(requestParameters: BackupEnvApiEnvJobGroupIdBackupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.backupEnvApiEnvJobGroupIdBackupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Close Env
     */
    async closeEnvApiEnvJobGroupIdClosePostRaw(requestParameters: CloseEnvApiEnvJobGroupIdClosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling closeEnvApiEnvJobGroupIdClosePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/close`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Close Env
     */
    async closeEnvApiEnvJobGroupIdClosePost(requestParameters: CloseEnvApiEnvJobGroupIdClosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.closeEnvApiEnvJobGroupIdClosePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new simulator.
     * Create Simulator
     */
    async createSimulatorApiEnvSimulatorsPostRaw(requestParameters: CreateSimulatorApiEnvSimulatorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['createSimulatorRequest'] == null) {
            throw new runtime.RequiredError(
                'createSimulatorRequest',
                'Required parameter "createSimulatorRequest" was null or undefined when calling createSimulatorApiEnvSimulatorsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/simulators`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSimulatorRequestToJSON(requestParameters['createSimulatorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a new simulator.
     * Create Simulator
     */
    async createSimulatorApiEnvSimulatorsPost(requestParameters: CreateSimulatorApiEnvSimulatorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createSimulatorApiEnvSimulatorsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Evaluate the session.
     * Evaluate Session
     */
    async evaluateSessionApiEnvSessionSessionIdEvaluatePostRaw(requestParameters: EvaluateSessionApiEnvSessionSessionIdEvaluatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling evaluateSessionApiEnvSessionSessionIdEvaluatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/session/{session_id}/evaluate`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EvaluateRequestToJSON(requestParameters['evaluateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Evaluate the session.
     * Evaluate Session
     */
    async evaluateSessionApiEnvSessionSessionIdEvaluatePost(requestParameters: EvaluateSessionApiEnvSessionSessionIdEvaluatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.evaluateSessionApiEnvSessionSessionIdEvaluatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the active session for a job group.
     * Get Active Session
     */
    async getActiveSessionApiEnvJobGroupIdActiveSessionGetRaw(requestParameters: GetActiveSessionApiEnvJobGroupIdActiveSessionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling getActiveSessionApiEnvJobGroupIdActiveSessionGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/active_session`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the active session for a job group.
     * Get Active Session
     */
    async getActiveSessionApiEnvJobGroupIdActiveSessionGet(requestParameters: GetActiveSessionApiEnvJobGroupIdActiveSessionGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getActiveSessionApiEnvJobGroupIdActiveSessionGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the CDP URL for the environment.
     * Get Cdp Url
     */
    async getCdpUrlApiEnvJobGroupIdCdpUrlGetRaw(requestParameters: GetCdpUrlApiEnvJobGroupIdCdpUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling getCdpUrlApiEnvJobGroupIdCdpUrlGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/cdp_url`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the CDP URL for the environment.
     * Get Cdp Url
     */
    async getCdpUrlApiEnvJobGroupIdCdpUrlGet(requestParameters: GetCdpUrlApiEnvJobGroupIdCdpUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getCdpUrlApiEnvJobGroupIdCdpUrlGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Env State
     */
    async getEnvStateApiEnvJobGroupIdStateGetRaw(requestParameters: GetEnvStateApiEnvJobGroupIdStateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling getEnvStateApiEnvJobGroupIdStateGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/state`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Env State
     */
    async getEnvStateApiEnvJobGroupIdStateGet(requestParameters: GetEnvStateApiEnvJobGroupIdStateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getEnvStateApiEnvJobGroupIdStateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Job Status
     */
    async getJobStatusApiEnvJobGroupIdStatusGetRaw(requestParameters: GetJobStatusApiEnvJobGroupIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobStatusResponse>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling getJobStatusApiEnvJobGroupIdStatusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/status`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get Job Status
     */
    async getJobStatusApiEnvJobGroupIdStatusGet(requestParameters: GetJobStatusApiEnvJobGroupIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobStatusResponse> {
        const response = await this.getJobStatusApiEnvJobGroupIdStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the public URL for the environment.
     * Get Proxy Url
     */
    async getProxyUrlApiEnvJobGroupIdProxyUrlGetRaw(requestParameters: GetProxyUrlApiEnvJobGroupIdProxyUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling getProxyUrlApiEnvJobGroupIdProxyUrlGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/proxy_url`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the public URL for the environment.
     * Get Proxy Url
     */
    async getProxyUrlApiEnvJobGroupIdProxyUrlGet(requestParameters: GetProxyUrlApiEnvJobGroupIdProxyUrlGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getProxyUrlApiEnvJobGroupIdProxyUrlGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all simulators with optimized queries.
     * Get Simulators
     */
    async getSimulatorsApiEnvSimulatorsGetRaw(requestParameters: GetSimulatorsApiEnvSimulatorsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/simulators`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all simulators with optimized queries.
     * Get Simulators
     */
    async getSimulatorsApiEnvSimulatorsGet(requestParameters: GetSimulatorsApiEnvSimulatorsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.getSimulatorsApiEnvSimulatorsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check if the workers for this job group are ready and healthy.  Uses the persistent job ready notification service to wait for job readiness. Falls back to checking Redis if notification not received (in case we missed it). Raises 500 if job not ready after all checks. 
     * Get Worker Ready
     */
    async getWorkerReadyApiEnvJobIdWorkerReadyGetRaw(requestParameters: GetWorkerReadyApiEnvJobIdWorkerReadyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkerReadyResponse>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getWorkerReadyApiEnvJobIdWorkerReadyGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['timeout'] != null) {
            queryParameters['timeout'] = requestParameters['timeout'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_id}/worker_ready`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkerReadyResponseFromJSON(jsonValue));
    }

    /**
     * Check if the workers for this job group are ready and healthy.  Uses the persistent job ready notification service to wait for job readiness. Falls back to checking Redis if notification not received (in case we missed it). Raises 500 if job not ready after all checks. 
     * Get Worker Ready
     */
    async getWorkerReadyApiEnvJobIdWorkerReadyGet(requestParameters: GetWorkerReadyApiEnvJobIdWorkerReadyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkerReadyResponse> {
        const response = await this.getWorkerReadyApiEnvJobIdWorkerReadyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Log a state mutation or batch of mutations.
     * Log State Mutation
     */
    async logStateMutationApiEnvSessionIdLogPostRaw(requestParameters: LogStateMutationApiEnvSessionIdLogPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling logStateMutationApiEnvSessionIdLogPost().'
            );
        }

        if (requestParameters['log'] == null) {
            throw new runtime.RequiredError(
                'log',
                'Required parameter "log" was null or undefined when calling logStateMutationApiEnvSessionIdLogPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{session_id}/log`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogToJSON(requestParameters['log']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Log a state mutation or batch of mutations.
     * Log State Mutation
     */
    async logStateMutationApiEnvSessionIdLogPost(requestParameters: LogStateMutationApiEnvSessionIdLogPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.logStateMutationApiEnvSessionIdLogPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Make Env
     */
    async makeEnvApiEnvMake2PostRaw(requestParameters: MakeEnvApiEnvMake2PostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MakeEnvResponse>> {
        if (requestParameters['makeEnvRequest2'] == null) {
            throw new runtime.RequiredError(
                'makeEnvRequest2',
                'Required parameter "makeEnvRequest2" was null or undefined when calling makeEnvApiEnvMake2Post().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/make2`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MakeEnvRequest2ToJSON(requestParameters['makeEnvRequest2']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MakeEnvResponseFromJSON(jsonValue));
    }

    /**
     * Make Env
     */
    async makeEnvApiEnvMake2Post(requestParameters: MakeEnvApiEnvMake2PostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MakeEnvResponse> {
        const response = await this.makeEnvApiEnvMake2PostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reset the environment with an optional task.
     * Reset Env
     */
    async resetEnvApiEnvJobGroupIdResetPostRaw(requestParameters: ResetEnvApiEnvJobGroupIdResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobGroupId'] == null) {
            throw new runtime.RequiredError(
                'jobGroupId',
                'Required parameter "jobGroupId" was null or undefined when calling resetEnvApiEnvJobGroupIdResetPost().'
            );
        }

        if (requestParameters['resetEnvRequest'] == null) {
            throw new runtime.RequiredError(
                'resetEnvRequest',
                'Required parameter "resetEnvRequest" was null or undefined when calling resetEnvApiEnvJobGroupIdResetPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_group_id}/reset`;
        urlPath = urlPath.replace(`{${"job_group_id"}}`, encodeURIComponent(String(requestParameters['jobGroupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetEnvRequestToJSON(requestParameters['resetEnvRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Reset the environment with an optional task.
     * Reset Env
     */
    async resetEnvApiEnvJobGroupIdResetPost(requestParameters: ResetEnvApiEnvJobGroupIdResetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.resetEnvApiEnvJobGroupIdResetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Score the environment.
     * Score Env
     */
    async scoreEnvApiEnvSessionSessionIdScorePostRaw(requestParameters: ScoreEnvApiEnvSessionSessionIdScorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling scoreEnvApiEnvSessionSessionIdScorePost().'
            );
        }

        if (requestParameters['scoreRequest'] == null) {
            throw new runtime.RequiredError(
                'scoreRequest',
                'Required parameter "scoreRequest" was null or undefined when calling scoreEnvApiEnvSessionSessionIdScorePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/session/{session_id}/score`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScoreRequestToJSON(requestParameters['scoreRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Score the environment.
     * Score Env
     */
    async scoreEnvApiEnvSessionSessionIdScorePost(requestParameters: ScoreEnvApiEnvSessionSessionIdScorePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.scoreEnvApiEnvSessionSessionIdScorePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a heartbeat to keep the environment session alive.
     * Send Heartbeat
     */
    async sendHeartbeatApiEnvJobIdHeartbeatPostRaw(requestParameters: SendHeartbeatApiEnvJobIdHeartbeatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling sendHeartbeatApiEnvJobIdHeartbeatPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/env/{job_id}/heartbeat`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send a heartbeat to keep the environment session alive.
     * Send Heartbeat
     */
    async sendHeartbeatApiEnvJobIdHeartbeatPost(requestParameters: SendHeartbeatApiEnvJobIdHeartbeatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.sendHeartbeatApiEnvJobIdHeartbeatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
