/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateSimulatorRepositoryRequest {
    simulatorId: number;
    authorization?: string;
    xInternalService?: string;
}

export interface GetAccessibleSimulatorsRequest {
    authorization?: string;
    xInternalService?: string;
}

export interface GetGiteaCredentialsRequest {
    authorization?: string;
    xInternalService?: string;
}

export interface GetMyGiteaInfoRequest {
    authorization?: string;
    xInternalService?: string;
}

export interface GetSimulatorRepositoryRequest {
    simulatorId: number;
    authorization?: string;
    xInternalService?: string;
}

/**
 * 
 */
export class GiteaApi extends runtime.BaseAPI {

    /**
     * Create a repository for a simulator (only if it doesn\'t exist)
     * Create Simulator Repository
     */
    async createSimulatorRepositoryRaw(requestParameters: CreateSimulatorRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['simulatorId'] == null) {
            throw new runtime.RequiredError(
                'simulatorId',
                'Required parameter "simulatorId" was null or undefined when calling createSimulatorRepository().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/gitea/simulators/{simulator_id}/repo`;
        urlPath = urlPath.replace(`{${"simulator_id"}}`, encodeURIComponent(String(requestParameters['simulatorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a repository for a simulator (only if it doesn\'t exist)
     * Create Simulator Repository
     */
    async createSimulatorRepository(requestParameters: CreateSimulatorRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createSimulatorRepositoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get simulators that user has access to view repos for
     * Get Accessible Simulators
     */
    async getAccessibleSimulatorsRaw(requestParameters: GetAccessibleSimulatorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/gitea/simulators`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get simulators that user has access to view repos for
     * Get Accessible Simulators
     */
    async getAccessibleSimulators(requestParameters: GetAccessibleSimulatorsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.getAccessibleSimulatorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Gitea credentials for the organization
     * Get Gitea Credentials
     */
    async getGiteaCredentialsRaw(requestParameters: GetGiteaCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/gitea/credentials`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get Gitea credentials for the organization
     * Get Gitea Credentials
     */
    async getGiteaCredentials(requestParameters: GetGiteaCredentialsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getGiteaCredentialsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the current user\'s Gitea info (auto-provisions if needed)
     * Get My Gitea Info
     */
    async getMyGiteaInfoRaw(requestParameters: GetMyGiteaInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/gitea/my-info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the current user\'s Gitea info (auto-provisions if needed)
     * Get My Gitea Info
     */
    async getMyGiteaInfo(requestParameters: GetMyGiteaInfoRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getMyGiteaInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get repository details for a specific simulator
     * Get Simulator Repository
     */
    async getSimulatorRepositoryRaw(requestParameters: GetSimulatorRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['simulatorId'] == null) {
            throw new runtime.RequiredError(
                'simulatorId',
                'Required parameter "simulatorId" was null or undefined when calling getSimulatorRepository().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/gitea/simulators/{simulator_id}/repo`;
        urlPath = urlPath.replace(`{${"simulator_id"}}`, encodeURIComponent(String(requestParameters['simulatorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get repository details for a specific simulator
     * Get Simulator Repository
     */
    async getSimulatorRepository(requestParameters: GetSimulatorRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getSimulatorRepositoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
