/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DbConfigResponse,
  HTTPValidationError,
  SimulatorListItem,
  SimulatorVersionsResponse,
} from '../models/index';
import {
    DbConfigResponseFromJSON,
    DbConfigResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SimulatorListItemFromJSON,
    SimulatorListItemToJSON,
    SimulatorVersionsResponseFromJSON,
    SimulatorVersionsResponseToJSON,
} from '../models/index';

export interface GetSimulatorDbConfigRequest {
    artifactId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface GetSimulatorFlowsRequest {
    artifactId: string;
    authorization?: string;
    xInternalService?: string;
}

export interface GetSimulatorVersionsRequest {
    simulatorName: string;
    includeCheckpoints?: boolean;
    authorization?: string;
    xInternalService?: string;
}

/**
 * 
 */
export class SimulatorApi extends runtime.BaseAPI {

    /**
     * Get database configuration from a simulator artifact\'s plato config.  Parses the YAML plato_config and extracts the database listener configuration. The plato_config contains a single dataset configuration (anchors are already resolved). 
     * Get Db Config
     */
    async getSimulatorDbConfigRaw(requestParameters: GetSimulatorDbConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DbConfigResponse>> {
        if (requestParameters['artifactId'] == null) {
            throw new runtime.RequiredError(
                'artifactId',
                'Required parameter "artifactId" was null or undefined when calling getSimulatorDbConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/simulator/{artifact_id}/db_config`;
        urlPath = urlPath.replace(`{${"artifact_id"}}`, encodeURIComponent(String(requestParameters['artifactId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DbConfigResponseFromJSON(jsonValue));
    }

    /**
     * Get database configuration from a simulator artifact\'s plato config.  Parses the YAML plato_config and extracts the database listener configuration. The plato_config contains a single dataset configuration (anchors are already resolved). 
     * Get Db Config
     */
    async getSimulatorDbConfig(requestParameters: GetSimulatorDbConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DbConfigResponse> {
        const response = await this.getSimulatorDbConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Env Flows
     */
    async getSimulatorFlowsRaw(requestParameters: GetSimulatorFlowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['artifactId'] == null) {
            throw new runtime.RequiredError(
                'artifactId',
                'Required parameter "artifactId" was null or undefined when calling getSimulatorFlows().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/simulator/{artifact_id}/flows`;
        urlPath = urlPath.replace(`{${"artifact_id"}}`, encodeURIComponent(String(requestParameters['artifactId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Env Flows
     */
    async getSimulatorFlows(requestParameters: GetSimulatorFlowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSimulatorFlowsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all versions for a specific simulator across all datasets
     * Get Simulator Versions
     */
    async getSimulatorVersionsRaw(requestParameters: GetSimulatorVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimulatorVersionsResponse>> {
        if (requestParameters['simulatorName'] == null) {
            throw new runtime.RequiredError(
                'simulatorName',
                'Required parameter "simulatorName" was null or undefined when calling getSimulatorVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeCheckpoints'] != null) {
            queryParameters['include_checkpoints'] = requestParameters['includeCheckpoints'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (requestParameters['xInternalService'] != null) {
            headerParameters['X-Internal-Service'] = String(requestParameters['xInternalService']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/simulator/{simulator_name}/versions`;
        urlPath = urlPath.replace(`{${"simulator_name"}}`, encodeURIComponent(String(requestParameters['simulatorName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimulatorVersionsResponseFromJSON(jsonValue));
    }

    /**
     * Get all versions for a specific simulator across all datasets
     * Get Simulator Versions
     */
    async getSimulatorVersions(requestParameters: GetSimulatorVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimulatorVersionsResponse> {
        const response = await this.getSimulatorVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of all simulators from database
     * List Simulators
     */
    async listSimulatorsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SimulatorListItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/simulator/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SimulatorListItemFromJSON));
    }

    /**
     * Get list of all simulators from database
     * List Simulators
     */
    async listSimulators(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SimulatorListItem>> {
        const response = await this.listSimulatorsRaw(initOverrides);
        return await response.value();
    }

}
