/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetTestcasesRequest {
    startPath?: string | null;
    testCaseSetIds?: string | null;
    name?: string | null;
    prompt?: string | null;
    mode?: string | null;
    page?: number | null;
    pageSize?: number;
    simulatorId?: number | null;
    simulatorName?: string | null;
    testCasePublicId?: string | null;
    scoringConfigType?: string | null;
    isAssigned?: boolean | null;
    isSample?: boolean | null;
    rejected?: boolean | null;
    excludeAssignedToAnnotators?: boolean | null;
}

/**
 * 
 */
export class TestcasesApi extends runtime.BaseAPI {

    /**
     * Get Testcases
     */
    async getTestcasesRaw(requestParameters: GetTestcasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['startPath'] != null) {
            queryParameters['start_path'] = requestParameters['startPath'];
        }

        if (requestParameters['testCaseSetIds'] != null) {
            queryParameters['test_case_set_ids'] = requestParameters['testCaseSetIds'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['prompt'] != null) {
            queryParameters['prompt'] = requestParameters['prompt'];
        }

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['simulatorId'] != null) {
            queryParameters['simulator_id'] = requestParameters['simulatorId'];
        }

        if (requestParameters['simulatorName'] != null) {
            queryParameters['simulator_name'] = requestParameters['simulatorName'];
        }

        if (requestParameters['testCasePublicId'] != null) {
            queryParameters['test_case_public_id'] = requestParameters['testCasePublicId'];
        }

        if (requestParameters['scoringConfigType'] != null) {
            queryParameters['scoring_config_type'] = requestParameters['scoringConfigType'];
        }

        if (requestParameters['isAssigned'] != null) {
            queryParameters['is_assigned'] = requestParameters['isAssigned'];
        }

        if (requestParameters['isSample'] != null) {
            queryParameters['is_sample'] = requestParameters['isSample'];
        }

        if (requestParameters['rejected'] != null) {
            queryParameters['rejected'] = requestParameters['rejected'];
        }

        if (requestParameters['excludeAssignedToAnnotators'] != null) {
            queryParameters['exclude_assigned_to_annotators'] = requestParameters['excludeAssignedToAnnotators'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/testcases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Testcases
     */
    async getTestcases(requestParameters: GetTestcasesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getTestcasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
