/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRequest {
    lastNHours?: number;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Get comprehensive session information for the user\'s organization.  Args:     last_n_hours: Number of hours to look back for peak calculation (default: 1)  Returns:     Dictionary containing:     - running_sessions: Count of currently running sessions     - pending_sessions: Count of sessions that are not ended but have status != RUN_STARTED     - peak_running_count: Peak number of running sessions within the past last_n_hours period 
     * Get Organization Running Sessions Endpoint
     */
    async getOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRaw(requestParameters: GetOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['lastNHours'] != null) {
            queryParameters['last_n_hours'] = requestParameters['lastNHours'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/user/organization/running-sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get comprehensive session information for the user\'s organization.  Args:     last_n_hours: Number of hours to look back for peak calculation (default: 1)  Returns:     Dictionary containing:     - running_sessions: Count of currently running sessions     - pending_sessions: Count of sessions that are not ended but have status != RUN_STARTED     - peak_running_count: Peak number of running sessions within the past last_n_hours period 
     * Get Organization Running Sessions Endpoint
     */
    async getOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGet(requestParameters: GetOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
