/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseStructuredRunLog
 */
export interface BaseStructuredRunLog {
    /**
     * 
     * @type {string}
     * @memberof BaseStructuredRunLog
     */
    source?: BaseStructuredRunLogSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof BaseStructuredRunLog
     */
    type?: BaseStructuredRunLogTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BaseStructuredRunLog
     */
    timestamp?: string;
}


/**
 * @export
 */
export const BaseStructuredRunLogSourceEnum = {
    System: 'system',
    Agent: 'agent',
    Simulator: 'simulator'
} as const;
export type BaseStructuredRunLogSourceEnum = typeof BaseStructuredRunLogSourceEnum[keyof typeof BaseStructuredRunLogSourceEnum];

/**
 * @export
 */
export const BaseStructuredRunLogTypeEnum = {
    Info: 'info',
    Warning: 'warning',
    Error: 'error',
    Answer: 'answer',
    Action: 'action',
    StateMutation: 'state_mutation',
    OodRequest: 'ood_request',
    ScreenRecordingStarted: 'screen_recording_started'
} as const;
export type BaseStructuredRunLogTypeEnum = typeof BaseStructuredRunLogTypeEnum[keyof typeof BaseStructuredRunLogTypeEnum];


/**
 * Check if a given object implements the BaseStructuredRunLog interface.
 */
export function instanceOfBaseStructuredRunLog(value: object): value is BaseStructuredRunLog {
    return true;
}

export function BaseStructuredRunLogFromJSON(json: any): BaseStructuredRunLog {
    return BaseStructuredRunLogFromJSONTyped(json, false);
}

export function BaseStructuredRunLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseStructuredRunLog {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'type': json['type'] == null ? undefined : json['type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseStructuredRunLogToJSON(json: any): BaseStructuredRunLog {
    return BaseStructuredRunLogToJSONTyped(json, false);
}

export function BaseStructuredRunLogToJSONTyped(value?: BaseStructuredRunLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'type': value['type'],
        'timestamp': value['timestamp'],
    };
}

