/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseScoringConfig
 */
export interface BaseScoringConfig {
    /**
     * 
     * @type {string}
     * @memberof BaseScoringConfig
     */
    type: BaseScoringConfigTypeEnum;
}


/**
 * @export
 */
export const BaseScoringConfigTypeEnum = {
    OfflineStep: 'offline_step',
    OfflineExactActionMatch: 'offline_exact_action_match',
    OfflineExactStateMatch: 'offline_exact_state_match',
    OfflineExactOutputMatch: 'offline_exact_output_match',
    PageActionSequence: 'page_action_sequence',
    HumanInTheLoop: 'human_in_the_loop',
    Api: 'api',
    Criteria: 'criteria',
    RealEvalsStateCheck: 'real_evals_state_check',
    RealEvalsResponseCheck: 'real_evals_response_check',
    Composite: 'composite',
    Custom: 'custom',
    StateMutationMatch: 'state_mutation_match',
    SystemScoring: 'system_scoring',
    JsonSchema: 'json_schema'
} as const;
export type BaseScoringConfigTypeEnum = typeof BaseScoringConfigTypeEnum[keyof typeof BaseScoringConfigTypeEnum];


/**
 * Check if a given object implements the BaseScoringConfig interface.
 */
export function instanceOfBaseScoringConfig(value: object): value is BaseScoringConfig {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function BaseScoringConfigFromJSON(json: any): BaseScoringConfig {
    return BaseScoringConfigFromJSONTyped(json, false);
}

export function BaseScoringConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseScoringConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function BaseScoringConfigToJSON(json: any): BaseScoringConfig {
    return BaseScoringConfigToJSONTyped(json, false);
}

export function BaseScoringConfigToJSONTyped(value?: BaseScoringConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

