/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseStructuredRunLog } from './BaseStructuredRunLog';
import {
    BaseStructuredRunLogFromJSON,
    BaseStructuredRunLogFromJSONTyped,
    BaseStructuredRunLogToJSON,
    BaseStructuredRunLogToJSONTyped,
} from './BaseStructuredRunLog';

/**
 * 
 * @export
 * @interface BatchLogRequest
 */
export interface BatchLogRequest {
    /**
     * 
     * @type {string}
     * @memberof BatchLogRequest
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof BatchLogRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof BatchLogRequest
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof BatchLogRequest
     */
    sessionId: string;
    /**
     * 
     * @type {Array<BaseStructuredRunLog>}
     * @memberof BatchLogRequest
     */
    mutations: Array<BaseStructuredRunLog>;
    /**
     * 
     * @type {number}
     * @memberof BatchLogRequest
     */
    count: number;
}

/**
 * Check if a given object implements the BatchLogRequest interface.
 */
export function instanceOfBatchLogRequest(value: object): value is BatchLogRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('mutations' in value) || value['mutations'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function BatchLogRequestFromJSON(json: any): BatchLogRequest {
    return BatchLogRequestFromJSONTyped(json, false);
}

export function BatchLogRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchLogRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'type': json['type'],
        'timestamp': json['timestamp'],
        'sessionId': json['session_id'],
        'mutations': ((json['mutations'] as Array<any>).map(BaseStructuredRunLogFromJSON)),
        'count': json['count'],
    };
}

export function BatchLogRequestToJSON(json: any): BatchLogRequest {
    return BatchLogRequestToJSONTyped(json, false);
}

export function BatchLogRequestToJSONTyped(value?: BatchLogRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'type': value['type'],
        'timestamp': value['timestamp'],
        'session_id': value['sessionId'],
        'mutations': ((value['mutations'] as Array<any>).map(BaseStructuredRunLogToJSON)),
        'count': value['count'],
    };
}

