/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimulatorConfig } from './SimulatorConfig';
import {
    SimulatorConfigFromJSON,
    SimulatorConfigFromJSONTyped,
    SimulatorConfigToJSON,
    SimulatorConfigToJSONTyped,
} from './SimulatorConfig';

/**
 * 
 * @export
 * @interface CreateSimulatorRequest
 */
export interface CreateSimulatorRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSimulatorRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSimulatorRequest
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSimulatorRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSimulatorRequest
     */
    imgUrl?: string | null;
    /**
     * 
     * @type {SimulatorConfig}
     * @memberof CreateSimulatorRequest
     */
    config: SimulatorConfig;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSimulatorRequest
     */
    ancestors?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSimulatorRequest
     */
    enabled?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSimulatorRequest
     */
    simType: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSimulatorRequest
     */
    jobName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateSimulatorRequest
     */
    internalAppPort?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSimulatorRequest
     */
    supportedProviders?: Array<string> | null;
}

/**
 * Check if a given object implements the CreateSimulatorRequest interface.
 */
export function instanceOfCreateSimulatorRequest(value: object): value is CreateSimulatorRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('simType' in value) || value['simType'] === undefined) return false;
    return true;
}

export function CreateSimulatorRequestFromJSON(json: any): CreateSimulatorRequest {
    return CreateSimulatorRequestFromJSONTyped(json, false);
}

export function CreateSimulatorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSimulatorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'imgUrl': json['imgUrl'] == null ? undefined : json['imgUrl'],
        'config': SimulatorConfigFromJSON(json['config']),
        'ancestors': json['ancestors'] == null ? undefined : json['ancestors'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'simType': json['simType'],
        'jobName': json['jobName'] == null ? undefined : json['jobName'],
        'internalAppPort': json['internalAppPort'] == null ? undefined : json['internalAppPort'],
        'supportedProviders': json['supportedProviders'] == null ? undefined : json['supportedProviders'],
    };
}

export function CreateSimulatorRequestToJSON(json: any): CreateSimulatorRequest {
    return CreateSimulatorRequestToJSONTyped(json, false);
}

export function CreateSimulatorRequestToJSONTyped(value?: CreateSimulatorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'description': value['description'],
        'imgUrl': value['imgUrl'],
        'config': SimulatorConfigToJSON(value['config']),
        'ancestors': value['ancestors'],
        'enabled': value['enabled'],
        'simType': value['simType'],
        'jobName': value['jobName'],
        'internalAppPort': value['internalAppPort'],
        'supportedProviders': value['supportedProviders'],
    };
}

