/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Database configuration from plato config
 * @export
 * @interface DbConfigResponse
 */
export interface DbConfigResponse {
    /**
     * 
     * @type {string}
     * @memberof DbConfigResponse
     */
    dbType: string;
    /**
     * 
     * @type {number}
     * @memberof DbConfigResponse
     */
    dbPort: number;
    /**
     * 
     * @type {string}
     * @memberof DbConfigResponse
     */
    dbUser: string;
    /**
     * 
     * @type {string}
     * @memberof DbConfigResponse
     */
    dbPassword: string;
    /**
     * 
     * @type {string}
     * @memberof DbConfigResponse
     */
    dbDatabase: string;
}

/**
 * Check if a given object implements the DbConfigResponse interface.
 */
export function instanceOfDbConfigResponse(value: object): value is DbConfigResponse {
    if (!('dbType' in value) || value['dbType'] === undefined) return false;
    if (!('dbPort' in value) || value['dbPort'] === undefined) return false;
    if (!('dbUser' in value) || value['dbUser'] === undefined) return false;
    if (!('dbPassword' in value) || value['dbPassword'] === undefined) return false;
    if (!('dbDatabase' in value) || value['dbDatabase'] === undefined) return false;
    return true;
}

export function DbConfigResponseFromJSON(json: any): DbConfigResponse {
    return DbConfigResponseFromJSONTyped(json, false);
}

export function DbConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dbType': json['db_type'],
        'dbPort': json['db_port'],
        'dbUser': json['db_user'],
        'dbPassword': json['db_password'],
        'dbDatabase': json['db_database'],
    };
}

export function DbConfigResponseToJSON(json: any): DbConfigResponse {
    return DbConfigResponseToJSONTyped(json, false);
}

export function DbConfigResponseToJSONTyped(value?: DbConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'db_type': value['dbType'],
        'db_port': value['dbPort'],
        'db_user': value['dbUser'],
        'db_password': value['dbPassword'],
        'db_database': value['dbDatabase'],
    };
}

