/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response
 */
export interface GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response {
    /**
     * Event type
     * @type {string}
     * @memberof GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response
     */
    type: GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseTypeEnum;
    /**
     * Whether the operation succeeded
     * @type {boolean}
     * @memberof GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response
     */
    success?: boolean;
    /**
     * Human-readable message
     * @type {string}
     * @memberof GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response
     */
    message?: string;
    /**
     * Error details if failed
     * @type {string}
     * @memberof GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response
     */
    error?: string;
}


/**
 * @export
 */
export const GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseTypeEnum = {
    Connected: 'connected',
    Progress: 'progress',
    Complete: 'complete',
    Error: 'error'
} as const;
export type GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseTypeEnum = typeof GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseTypeEnum[keyof typeof GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseTypeEnum];


/**
 * Check if a given object implements the GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response interface.
 */
export function instanceOfGetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response(value: object): value is GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseFromJSON(json: any): GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response {
    return GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseFromJSONTyped(json, false);
}

export function GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseToJSON(json: any): GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response {
    return GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseToJSONTyped(json, false);
}

export function GetOperationEventsApiPublicBuildEventsCorrelationIdGet200ResponseToJSONTyped(value?: GetOperationEventsApiPublicBuildEventsCorrelationIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'success': value['success'],
        'message': value['message'],
        'error': value['error'],
    };
}

