/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for job status endpoint.
 * @export
 * @interface JobStatusResponse
 */
export interface JobStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof JobStatusResponse
     */
    statusReason: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobStatusResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobStatusResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the JobStatusResponse interface.
 */
export function instanceOfJobStatusResponse(value: object): value is JobStatusResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusReason' in value) || value['statusReason'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function JobStatusResponseFromJSON(json: any): JobStatusResponse {
    return JobStatusResponseFromJSONTyped(json, false);
}

export function JobStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'statusReason': json['status_reason'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function JobStatusResponseToJSON(json: any): JobStatusResponse {
    return JobStatusResponseToJSONTyped(json, false);
}

export function JobStatusResponseToJSONTyped(value?: JobStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'status_reason': value['statusReason'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

