/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MakeEnvRequest2
 */
export interface MakeEnvRequest2 {
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    interfaceType: MakeEnvRequest2InterfaceTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof MakeEnvRequest2
     */
    interfaceWidth?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MakeEnvRequest2
     */
    interfaceHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    source: string;
    /**
     * 
     * @type {boolean}
     * @memberof MakeEnvRequest2
     */
    openPageOnStart?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    envId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MakeEnvRequest2
     */
    envConfig: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof MakeEnvRequest2
     */
    recordNetworkRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MakeEnvRequest2
     */
    recordActions?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof MakeEnvRequest2
     */
    loadChromeExtensions?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof MakeEnvRequest2
     */
    keepalive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    alias?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MakeEnvRequest2
     */
    fast?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    tag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    dataset?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MakeEnvRequest2
     */
    artifactId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MakeEnvRequest2
     */
    timeout?: number;
}


/**
 * @export
 */
export const MakeEnvRequest2InterfaceTypeEnum = {
    Browser: 'browser',
    Computer: 'computer',
    Noop: 'noop'
} as const;
export type MakeEnvRequest2InterfaceTypeEnum = typeof MakeEnvRequest2InterfaceTypeEnum[keyof typeof MakeEnvRequest2InterfaceTypeEnum];


/**
 * Check if a given object implements the MakeEnvRequest2 interface.
 */
export function instanceOfMakeEnvRequest2(value: object): value is MakeEnvRequest2 {
    if (!('interfaceType' in value) || value['interfaceType'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('envId' in value) || value['envId'] === undefined) return false;
    if (!('envConfig' in value) || value['envConfig'] === undefined) return false;
    return true;
}

export function MakeEnvRequest2FromJSON(json: any): MakeEnvRequest2 {
    return MakeEnvRequest2FromJSONTyped(json, false);
}

export function MakeEnvRequest2FromJSONTyped(json: any, ignoreDiscriminator: boolean): MakeEnvRequest2 {
    if (json == null) {
        return json;
    }
    return {
        
        'interfaceType': json['interface_type'],
        'interfaceWidth': json['interface_width'] == null ? undefined : json['interface_width'],
        'interfaceHeight': json['interface_height'] == null ? undefined : json['interface_height'],
        'source': json['source'],
        'openPageOnStart': json['open_page_on_start'] == null ? undefined : json['open_page_on_start'],
        'envId': json['env_id'],
        'envConfig': json['env_config'],
        'recordNetworkRequests': json['record_network_requests'] == null ? undefined : json['record_network_requests'],
        'recordActions': json['record_actions'] == null ? undefined : json['record_actions'],
        'loadChromeExtensions': json['load_chrome_extensions'] == null ? undefined : json['load_chrome_extensions'],
        'keepalive': json['keepalive'] == null ? undefined : json['keepalive'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'fast': json['fast'] == null ? undefined : json['fast'],
        'version': json['version'] == null ? undefined : json['version'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'dataset': json['dataset'] == null ? undefined : json['dataset'],
        'artifactId': json['artifact_id'] == null ? undefined : json['artifact_id'],
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
    };
}

export function MakeEnvRequest2ToJSON(json: any): MakeEnvRequest2 {
    return MakeEnvRequest2ToJSONTyped(json, false);
}

export function MakeEnvRequest2ToJSONTyped(value?: MakeEnvRequest2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interface_type': value['interfaceType'],
        'interface_width': value['interfaceWidth'],
        'interface_height': value['interfaceHeight'],
        'source': value['source'],
        'open_page_on_start': value['openPageOnStart'],
        'env_id': value['envId'],
        'env_config': value['envConfig'],
        'record_network_requests': value['recordNetworkRequests'],
        'record_actions': value['recordActions'],
        'load_chrome_extensions': value['loadChromeExtensions'],
        'keepalive': value['keepalive'],
        'alias': value['alias'],
        'fast': value['fast'],
        'version': value['version'],
        'tag': value['tag'],
        'dataset': value['dataset'],
        'artifact_id': value['artifactId'],
        'timeout': value['timeout'],
    };
}

