/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResetEnvTask } from './ResetEnvTask';
import {
    ResetEnvTaskFromJSON,
    ResetEnvTaskFromJSONTyped,
    ResetEnvTaskToJSON,
    ResetEnvTaskToJSONTyped,
} from './ResetEnvTask';

/**
 * 
 * @export
 * @interface ResetEnvRequest
 */
export interface ResetEnvRequest {
    /**
     * 
     * @type {ResetEnvTask}
     * @memberof ResetEnvRequest
     */
    task?: ResetEnvTask | null;
    /**
     * 
     * @type {string}
     * @memberof ResetEnvRequest
     */
    agentVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResetEnvRequest
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResetEnvRequest
     */
    source?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResetEnvRequest
     */
    loadBrowserState?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ResetEnvRequest
     */
    viewportWidth?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ResetEnvRequest
     */
    viewportHeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ResetEnvRequest
     */
    testCasePublicId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResetEnvRequest
     */
    replayedFromSessionId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ResetEnvRequest
     */
    userId?: number | null;
}

/**
 * Check if a given object implements the ResetEnvRequest interface.
 */
export function instanceOfResetEnvRequest(value: object): value is ResetEnvRequest {
    return true;
}

export function ResetEnvRequestFromJSON(json: any): ResetEnvRequest {
    return ResetEnvRequestFromJSONTyped(json, false);
}

export function ResetEnvRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetEnvRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : ResetEnvTaskFromJSON(json['task']),
        'agentVersion': json['agent_version'] == null ? undefined : json['agent_version'],
        'model': json['model'] == null ? undefined : json['model'],
        'source': json['source'] == null ? undefined : json['source'],
        'loadBrowserState': json['load_browser_state'] == null ? undefined : json['load_browser_state'],
        'viewportWidth': json['viewport_width'] == null ? undefined : json['viewport_width'],
        'viewportHeight': json['viewport_height'] == null ? undefined : json['viewport_height'],
        'testCasePublicId': json['test_case_public_id'] == null ? undefined : json['test_case_public_id'],
        'replayedFromSessionId': json['replayed_from_session_id'] == null ? undefined : json['replayed_from_session_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function ResetEnvRequestToJSON(json: any): ResetEnvRequest {
    return ResetEnvRequestToJSONTyped(json, false);
}

export function ResetEnvRequestToJSONTyped(value?: ResetEnvRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': ResetEnvTaskToJSON(value['task']),
        'agent_version': value['agentVersion'],
        'model': value['model'],
        'source': value['source'],
        'load_browser_state': value['loadBrowserState'],
        'viewport_width': value['viewportWidth'],
        'viewport_height': value['viewportHeight'],
        'test_case_public_id': value['testCasePublicId'],
        'replayed_from_session_id': value['replayedFromSessionId'],
        'user_id': value['userId'],
    };
}

