/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupSandboxResponse
 */
export interface SetupSandboxResponse {
    /**
     * Status
     * @type {string}
     * @memberof SetupSandboxResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof SetupSandboxResponse
     */
    timestamp?: string | null;
    /**
     * Correlation ID for tracking
     * @type {string}
     * @memberof SetupSandboxResponse
     */
    correlationId: string;
    /**
     * SSH URL for connecting to sandbox
     * @type {string}
     * @memberof SetupSandboxResponse
     */
    sshUrl: string;
}

/**
 * Check if a given object implements the SetupSandboxResponse interface.
 */
export function instanceOfSetupSandboxResponse(value: object): value is SetupSandboxResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('correlationId' in value) || value['correlationId'] === undefined) return false;
    if (!('sshUrl' in value) || value['sshUrl'] === undefined) return false;
    return true;
}

export function SetupSandboxResponseFromJSON(json: any): SetupSandboxResponse {
    return SetupSandboxResponseFromJSONTyped(json, false);
}

export function SetupSandboxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupSandboxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'correlationId': json['correlation_id'],
        'sshUrl': json['ssh_url'],
    };
}

export function SetupSandboxResponseToJSON(json: any): SetupSandboxResponse {
    return SetupSandboxResponseToJSONTyped(json, false);
}

export function SetupSandboxResponseToJSONTyped(value?: SetupSandboxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'],
        'correlation_id': value['correlationId'],
        'ssh_url': value['sshUrl'],
    };
}

