/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Base class for mutation listener configurations.
 * @export
 * @interface SimConfigListener
 */
export interface SimConfigListener {
    /**
     * Listener type
     * @type {string}
     * @memberof SimConfigListener
     */
    type: SimConfigListenerTypeEnum;
}


/**
 * @export
 */
export const SimConfigListenerTypeEnum = {
    Db: 'db',
    Proxy: 'proxy',
    File: 'file'
} as const;
export type SimConfigListenerTypeEnum = typeof SimConfigListenerTypeEnum[keyof typeof SimConfigListenerTypeEnum];


/**
 * Check if a given object implements the SimConfigListener interface.
 */
export function instanceOfSimConfigListener(value: object): value is SimConfigListener {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SimConfigListenerFromJSON(json: any): SimConfigListener {
    return SimConfigListenerFromJSONTyped(json, false);
}

export function SimConfigListenerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimConfigListener {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function SimConfigListenerToJSON(json: any): SimConfigListener {
    return SimConfigListenerToJSONTyped(json, false);
}

export function SimConfigListenerToJSONTyped(value?: SimConfigListener | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

