/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Compute resource configuration for a simulator.
 * @export
 * @interface SimConfigCompute
 */
export interface SimConfigCompute {
    /**
     * vCPUs
     * @type {number}
     * @memberof SimConfigCompute
     */
    cpus?: number;
    /**
     * Memory in MB
     * @type {number}
     * @memberof SimConfigCompute
     */
    memory?: number;
    /**
     * Disk space in MB
     * @type {number}
     * @memberof SimConfigCompute
     */
    disk?: number;
    /**
     * Application port
     * @type {number}
     * @memberof SimConfigCompute
     */
    appPort?: number;
    /**
     * Plato messaging port
     * @type {number}
     * @memberof SimConfigCompute
     */
    platoMessagingPort?: number;
}

/**
 * Check if a given object implements the SimConfigCompute interface.
 */
export function instanceOfSimConfigCompute(value: object): value is SimConfigCompute {
    return true;
}

export function SimConfigComputeFromJSON(json: any): SimConfigCompute {
    return SimConfigComputeFromJSONTyped(json, false);
}

export function SimConfigComputeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimConfigCompute {
    if (json == null) {
        return json;
    }
    return {
        
        'cpus': json['cpus'] == null ? undefined : json['cpus'],
        'memory': json['memory'] == null ? undefined : json['memory'],
        'disk': json['disk'] == null ? undefined : json['disk'],
        'appPort': json['app_port'] == null ? undefined : json['app_port'],
        'platoMessagingPort': json['plato_messaging_port'] == null ? undefined : json['plato_messaging_port'],
    };
}

export function SimConfigComputeToJSON(json: any): SimConfigCompute {
    return SimConfigComputeToJSONTyped(json, false);
}

export function SimConfigComputeToJSONTyped(value?: SimConfigCompute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpus': value['cpus'],
        'memory': value['memory'],
        'disk': value['disk'],
        'app_port': value['appPort'],
        'plato_messaging_port': value['platoMessagingPort'],
    };
}

