/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata configuration for a simulator.
 * @export
 * @interface SimConfigMetadata
 */
export interface SimConfigMetadata {
    /**
     * Favicon URL
     * @type {string}
     * @memberof SimConfigMetadata
     */
    favicon?: string;
    /**
     * Name
     * @type {string}
     * @memberof SimConfigMetadata
     */
    name?: string;
    /**
     * Description
     * @type {string}
     * @memberof SimConfigMetadata
     */
    description?: string;
    /**
     * Source code URL
     * @type {string}
     * @memberof SimConfigMetadata
     */
    sourceCodeUrl?: string;
    /**
     * Start URL
     * @type {string}
     * @memberof SimConfigMetadata
     */
    startUrl?: string;
    /**
     * License
     * @type {string}
     * @memberof SimConfigMetadata
     */
    license?: string;
    /**
     * Variables
     * @type {Array<{ [key: string]: string; }>}
     * @memberof SimConfigMetadata
     */
    variables?: Array<{ [key: string]: string; }>;
    /**
     * 
     * @type {string}
     * @memberof SimConfigMetadata
     */
    flowsPath?: string | null;
}

/**
 * Check if a given object implements the SimConfigMetadata interface.
 */
export function instanceOfSimConfigMetadata(value: object): value is SimConfigMetadata {
    return true;
}

export function SimConfigMetadataFromJSON(json: any): SimConfigMetadata {
    return SimConfigMetadataFromJSONTyped(json, false);
}

export function SimConfigMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimConfigMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'favicon': json['favicon'] == null ? undefined : json['favicon'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'sourceCodeUrl': json['source_code_url'] == null ? undefined : json['source_code_url'],
        'startUrl': json['start_url'] == null ? undefined : json['start_url'],
        'license': json['license'] == null ? undefined : json['license'],
        'variables': json['variables'] == null ? undefined : json['variables'],
        'flowsPath': json['flows_path'] == null ? undefined : json['flows_path'],
    };
}

export function SimConfigMetadataToJSON(json: any): SimConfigMetadata {
    return SimConfigMetadataToJSONTyped(json, false);
}

export function SimConfigMetadataToJSONTyped(value?: SimConfigMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'favicon': value['favicon'],
        'name': value['name'],
        'description': value['description'],
        'source_code_url': value['sourceCodeUrl'],
        'start_url': value['startUrl'],
        'license': value['license'],
        'variables': value['variables'],
        'flows_path': value['flowsPath'],
    };
}

