/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Base class for simulator service configurations.
 * @export
 * @interface SimConfigService
 */
export interface SimConfigService {
    /**
     * Service type
     * @type {string}
     * @memberof SimConfigService
     */
    type: SimConfigServiceTypeEnum;
}


/**
 * @export
 */
export const SimConfigServiceTypeEnum = {
    DockerCompose: 'docker-compose',
    Docker: 'docker'
} as const;
export type SimConfigServiceTypeEnum = typeof SimConfigServiceTypeEnum[keyof typeof SimConfigServiceTypeEnum];


/**
 * Check if a given object implements the SimConfigService interface.
 */
export function instanceOfSimConfigService(value: object): value is SimConfigService {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SimConfigServiceFromJSON(json: any): SimConfigService {
    return SimConfigServiceFromJSONTyped(json, false);
}

export function SimConfigServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimConfigService {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function SimConfigServiceToJSON(json: any): SimConfigService {
    return SimConfigServiceToJSONTyped(json, false);
}

export function SimConfigServiceToJSONTyped(value?: SimConfigService | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

