/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulatorVersionDetails
 */
export interface SimulatorVersionDetails {
    /**
     * 
     * @type {string}
     * @memberof SimulatorVersionDetails
     */
    artifactId: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatorVersionDetails
     */
    version: string;
    /**
     * 
     * @type {Date}
     * @memberof SimulatorVersionDetails
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SimulatorVersionDetails
     */
    workerImage: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatorVersionDetails
     */
    ecsTaskDefinitionArn: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatorVersionDetails
     */
    snapshotS3Uri: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatorVersionDetails
     */
    dataset: string;
}

/**
 * Check if a given object implements the SimulatorVersionDetails interface.
 */
export function instanceOfSimulatorVersionDetails(value: object): value is SimulatorVersionDetails {
    if (!('artifactId' in value) || value['artifactId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('workerImage' in value) || value['workerImage'] === undefined) return false;
    if (!('ecsTaskDefinitionArn' in value) || value['ecsTaskDefinitionArn'] === undefined) return false;
    if (!('snapshotS3Uri' in value) || value['snapshotS3Uri'] === undefined) return false;
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    return true;
}

export function SimulatorVersionDetailsFromJSON(json: any): SimulatorVersionDetails {
    return SimulatorVersionDetailsFromJSONTyped(json, false);
}

export function SimulatorVersionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorVersionDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'artifactId': json['artifact_id'],
        'version': json['version'],
        'createdAt': (new Date(json['created_at'])),
        'workerImage': json['worker_image'],
        'ecsTaskDefinitionArn': json['ecs_task_definition_arn'],
        'snapshotS3Uri': json['snapshot_s3_uri'],
        'dataset': json['dataset'],
    };
}

export function SimulatorVersionDetailsToJSON(json: any): SimulatorVersionDetails {
    return SimulatorVersionDetailsToJSONTyped(json, false);
}

export function SimulatorVersionDetailsToJSONTyped(value?: SimulatorVersionDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artifact_id': value['artifactId'],
        'version': value['version'],
        'created_at': value['createdAt'].toISOString(),
        'worker_image': value['workerImage'],
        'ecs_task_definition_arn': value['ecsTaskDefinitionArn'],
        'snapshot_s3_uri': value['snapshotS3Uri'],
        'dataset': value['dataset'],
    };
}

