/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Authentication } from './Authentication';
import {
    AuthenticationFromJSON,
    AuthenticationFromJSONTyped,
    AuthenticationToJSON,
    AuthenticationToJSONTyped,
} from './Authentication';
import type { SimStatusHistory } from './SimStatusHistory';
import {
    SimStatusHistoryFromJSON,
    SimStatusHistoryFromJSONTyped,
    SimStatusHistoryToJSON,
    SimStatusHistoryToJSONTyped,
} from './SimStatusHistory';
import type { ChromeCookie } from './ChromeCookie';
import {
    ChromeCookieFromJSON,
    ChromeCookieFromJSONTyped,
    ChromeCookieToJSON,
    ChromeCookieToJSONTyped,
} from './ChromeCookie';

/**
 * 
 * @export
 * @interface SimulatorConfig
 */
export interface SimulatorConfig {
    /**
     * 
     * @type {string}
     * @memberof SimulatorConfig
     */
    type: SimulatorConfigTypeEnum;
    /**
     * 
     * @type {Array<ChromeCookie>}
     * @memberof SimulatorConfig
     */
    cookies?: Array<ChromeCookie> | null;
    /**
     * 
     * @type {Authentication}
     * @memberof SimulatorConfig
     */
    authentication?: Authentication | null;
    /**
     * 
     * @type {string}
     * @memberof SimulatorConfig
     */
    defaultStartPath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SimulatorConfig
     */
    status?: SimulatorConfigStatusEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof SimulatorConfig
     */
    envAssignees?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SimulatorConfig
     */
    envReviewAssignees?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SimulatorConfig
     */
    dataAssignees?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SimulatorConfig
     */
    dataReviewAssignees?: Array<number> | null;
    /**
     * 
     * @type {Array<SimStatusHistory>}
     * @memberof SimulatorConfig
     */
    statusHistory?: Array<SimStatusHistory> | null;
    /**
     * 
     * @type {number}
     * @memberof SimulatorConfig
     */
    assignedUserId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SimulatorConfig
     */
    notes?: string | null;
}


/**
 * @export
 */
export const SimulatorConfigTypeEnum = {
    Proxy: 'proxy',
    DockerApp: 'docker_app'
} as const;
export type SimulatorConfigTypeEnum = typeof SimulatorConfigTypeEnum[keyof typeof SimulatorConfigTypeEnum];

/**
 * @export
 */
export const SimulatorConfigStatusEnum = {
    Requested: 'requested',
    InProgress: 'in_progress',
    EnvironmentInProgress: 'environment_in_progress',
    EnvironmentReady: 'environment_ready',
    DataInProgress: 'data_in_progress',
    DataReady: 'data_ready',
    TasksInProgress: 'tasks_in_progress',
    NotStarted: 'not_started',
    EnvInProgress: 'env_in_progress',
    EnvReviewRequested: 'env_review_requested',
    EnvApproved: 'env_approved',
    DataReviewRequested: 'data_review_requested',
    Ready: 'ready',
    ReadyDisabledTesting: 'ready-disabled-testing',
    OutOfService: 'out_of_service'
} as const;
export type SimulatorConfigStatusEnum = typeof SimulatorConfigStatusEnum[keyof typeof SimulatorConfigStatusEnum];


/**
 * Check if a given object implements the SimulatorConfig interface.
 */
export function instanceOfSimulatorConfig(value: object): value is SimulatorConfig {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SimulatorConfigFromJSON(json: any): SimulatorConfig {
    return SimulatorConfigFromJSONTyped(json, false);
}

export function SimulatorConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'cookies': json['cookies'] == null ? undefined : ((json['cookies'] as Array<any>).map(ChromeCookieFromJSON)),
        'authentication': json['authentication'] == null ? undefined : AuthenticationFromJSON(json['authentication']),
        'defaultStartPath': json['default_start_path'] == null ? undefined : json['default_start_path'],
        'status': json['status'] == null ? undefined : json['status'],
        'envAssignees': json['env_assignees'] == null ? undefined : json['env_assignees'],
        'envReviewAssignees': json['env_review_assignees'] == null ? undefined : json['env_review_assignees'],
        'dataAssignees': json['data_assignees'] == null ? undefined : json['data_assignees'],
        'dataReviewAssignees': json['data_review_assignees'] == null ? undefined : json['data_review_assignees'],
        'statusHistory': json['status_history'] == null ? undefined : ((json['status_history'] as Array<any>).map(SimStatusHistoryFromJSON)),
        'assignedUserId': json['assigned_user_id'] == null ? undefined : json['assigned_user_id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function SimulatorConfigToJSON(json: any): SimulatorConfig {
    return SimulatorConfigToJSONTyped(json, false);
}

export function SimulatorConfigToJSONTyped(value?: SimulatorConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'cookies': value['cookies'] == null ? undefined : ((value['cookies'] as Array<any>).map(ChromeCookieToJSON)),
        'authentication': AuthenticationToJSON(value['authentication']),
        'default_start_path': value['defaultStartPath'],
        'status': value['status'],
        'env_assignees': value['envAssignees'],
        'env_review_assignees': value['envReviewAssignees'],
        'data_assignees': value['dataAssignees'],
        'data_review_assignees': value['dataReviewAssignees'],
        'status_history': value['statusHistory'] == null ? undefined : ((value['statusHistory'] as Array<any>).map(SimStatusHistoryToJSON)),
        'assigned_user_id': value['assignedUserId'],
        'notes': value['notes'],
    };
}

