/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulatorStatus
 */
export interface SimulatorStatus {
    /**
     * 
     * @type {string}
     * @memberof SimulatorStatus
     */
    simulatorName: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatorStatus
     */
    status?: string | null;
}

/**
 * Check if a given object implements the SimulatorStatus interface.
 */
export function instanceOfSimulatorStatus(value: object): value is SimulatorStatus {
    if (!('simulatorName' in value) || value['simulatorName'] === undefined) return false;
    return true;
}

export function SimulatorStatusFromJSON(json: any): SimulatorStatus {
    return SimulatorStatusFromJSONTyped(json, false);
}

export function SimulatorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'simulatorName': json['simulator_name'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function SimulatorStatusToJSON(json: any): SimulatorStatus {
    return SimulatorStatusToJSONTyped(json, false);
}

export function SimulatorStatusToJSONTyped(value?: SimulatorStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulator_name': value['simulatorName'],
        'status': value['status'],
    };
}

