/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimulatorVersionDetails } from './SimulatorVersionDetails';
import {
    SimulatorVersionDetailsFromJSON,
    SimulatorVersionDetailsFromJSONTyped,
    SimulatorVersionDetailsToJSON,
    SimulatorVersionDetailsToJSONTyped,
} from './SimulatorVersionDetails';

/**
 * 
 * @export
 * @interface SimulatorVersionsResponse
 */
export interface SimulatorVersionsResponse {
    /**
     * 
     * @type {string}
     * @memberof SimulatorVersionsResponse
     */
    simulatorName: string;
    /**
     * 
     * @type {Array<SimulatorVersionDetails>}
     * @memberof SimulatorVersionsResponse
     */
    versions: Array<SimulatorVersionDetails>;
    /**
     * 
     * @type {number}
     * @memberof SimulatorVersionsResponse
     */
    totalVersions: number;
}

/**
 * Check if a given object implements the SimulatorVersionsResponse interface.
 */
export function instanceOfSimulatorVersionsResponse(value: object): value is SimulatorVersionsResponse {
    if (!('simulatorName' in value) || value['simulatorName'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    if (!('totalVersions' in value) || value['totalVersions'] === undefined) return false;
    return true;
}

export function SimulatorVersionsResponseFromJSON(json: any): SimulatorVersionsResponse {
    return SimulatorVersionsResponseFromJSONTyped(json, false);
}

export function SimulatorVersionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorVersionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'simulatorName': json['simulator_name'],
        'versions': ((json['versions'] as Array<any>).map(SimulatorVersionDetailsFromJSON)),
        'totalVersions': json['total_versions'],
    };
}

export function SimulatorVersionsResponseToJSON(json: any): SimulatorVersionsResponse {
    return SimulatorVersionsResponseToJSONTyped(json, false);
}

export function SimulatorVersionsResponseToJSONTyped(value?: SimulatorVersionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulator_name': value['simulatorName'],
        'versions': ((value['versions'] as Array<any>).map(SimulatorVersionDetailsToJSON)),
        'total_versions': value['totalVersions'],
    };
}

