/* tslint:disable */
/* eslint-disable */
/**
 * Plato API
 * API for Plato platform - SDK routes only
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimConfigDataset } from './SimConfigDataset';
import {
    SimConfigDatasetFromJSON,
    SimConfigDatasetFromJSONTyped,
    SimConfigDatasetToJSON,
    SimConfigDatasetToJSONTyped,
} from './SimConfigDataset';

/**
 * 
 * @export
 * @interface VMManagementRequest
 */
export interface VMManagementRequest {
    /**
     * 
     * @type {string}
     * @memberof VMManagementRequest
     */
    service?: string | null;
    /**
     * Dataset name
     * @type {string}
     * @memberof VMManagementRequest
     */
    dataset: string;
    /**
     * 
     * @type {SimConfigDataset}
     * @memberof VMManagementRequest
     */
    platoDatasetConfig: SimConfigDataset;
    /**
     * Request timeout in seconds
     * @type {number}
     * @memberof VMManagementRequest
     */
    requestTimeout?: number;
}

/**
 * Check if a given object implements the VMManagementRequest interface.
 */
export function instanceOfVMManagementRequest(value: object): value is VMManagementRequest {
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('platoDatasetConfig' in value) || value['platoDatasetConfig'] === undefined) return false;
    return true;
}

export function VMManagementRequestFromJSON(json: any): VMManagementRequest {
    return VMManagementRequestFromJSONTyped(json, false);
}

export function VMManagementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMManagementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'] == null ? undefined : json['service'],
        'dataset': json['dataset'],
        'platoDatasetConfig': SimConfigDatasetFromJSON(json['plato_dataset_config']),
        'requestTimeout': json['request_timeout'] == null ? undefined : json['request_timeout'],
    };
}

export function VMManagementRequestToJSON(json: any): VMManagementRequest {
    return VMManagementRequestToJSONTyped(json, false);
}

export function VMManagementRequestToJSONTyped(value?: VMManagementRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'dataset': value['dataset'],
        'plato_dataset_config': SimConfigDatasetToJSON(value['platoDatasetConfig']),
        'request_timeout': value['requestTimeout'],
    };
}

