// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         authorization: "authorization",
 *         "X-Internal-Service": "X-Internal-Service",
 *         include_checkpoints: true
 *     }
 */
export interface GetSimulatorVersionsApiSimulatorSimulatorNameVersionsGetRequest {
    /** Include blockdiff checkpoint artifacts */
    include_checkpoints?: boolean;
    authorization?: string;
    "X-Internal-Service"?: string;
}
