// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CreateSnapshotRequest {
    service?: string;
    git_hash?: string;
    dataset?: string;
}
