// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../../index.js";

/**
 * @example
 *     {
 *         dataset: "dataset",
 *         plato_dataset_config: {
 *             compute: {
 *                 cpus: 1,
 *                 memory: 1,
 *                 disk: 1,
 *                 app_port: 1,
 *                 plato_messaging_port: 1
 *             },
 *             metadata: {
 *                 name: "name"
 *             }
 *         }
 *     }
 */
export interface CreateSandboxRequest {
    /** Dataset name (e.g., "base") */
    dataset: string;
    plato_dataset_config: Api.SimConfigDataset;
    /** Timeout in seconds for sandbox creation */
    timeout?: number;
    /** Wait time in seconds */
    wait_time?: number;
    /** Human-readable alias for the sandbox */
    alias?: string;
    /** Optional artifact ID to create sandbox from snapshot */
    artifact_id?: string;
    /** Service name */
    service?: string;
}
