// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         merge_mutations: true
 *     }
 */
export interface GetEnvironmentStateRequest {
    merge_mutations?: boolean;
}
