// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         source: "source",
 *         type: "type",
 *         message: {
 *             "key": "value"
 *         },
 *         timestamp: "timestamp"
 *     }
 */
export interface LogRequest {
    source: string;
    type: string;
    message: Record<string, unknown>;
    timestamp: string;
}
