// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         interface_type: "interface_type",
 *         env_id: "env_id"
 *     }
 */
export interface MakeEnvironmentRequest {
    interface_type: string;
    interface_width?: number;
    interface_height?: number;
    source?: string;
    open_page_on_start?: boolean;
    env_id: string;
    tag?: string;
    dataset?: string;
    artifact_id?: string;
    env_config?: Record<string, unknown>;
    record_network_requests?: boolean;
    record_actions?: boolean;
    keepalive?: boolean;
    alias?: string;
    fast?: boolean;
    version?: string;
}
