// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ssh_public_key: "ssh_public_key"
 *     }
 */
export interface SetupRootAccessRequest {
    /** SSH public key to install for root user */
    ssh_public_key: string;
    /** Timeout in seconds */
    timeout?: number;
}
