// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../../index.js";

/**
 * @example
 *     {
 *         dataset: "dataset",
 *         plato_dataset_config: {
 *             compute: {
 *                 cpus: 1,
 *                 memory: 1,
 *                 disk: 1,
 *                 app_port: 1,
 *                 plato_messaging_port: 1
 *             },
 *             metadata: {
 *                 name: "name"
 *             }
 *         }
 *     }
 */
export interface StartWorkerRequest {
    service?: string;
    dataset: string;
    plato_dataset_config: Api.SimConfigDataset;
    timeout?: number;
}
