// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Api from "../../../index.js";

export declare namespace Testcases {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Testcases {
    protected readonly _options: Testcases.Options;

    constructor(_options: Testcases.Options) {
        this._options = _options;
    }

    /**
     * @param {Api.GetTestcasesApiTestcasesGetRequest} request
     * @param {Testcases.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.testcases.getTestcasesApi({
     *         start_path: "start_path",
     *         test_case_set_ids: "test_case_set_ids",
     *         name: "name",
     *         prompt: "prompt",
     *         mode: "mode",
     *         page: 1,
     *         page_size: 1,
     *         simulator_id: 1,
     *         simulator_name: "simulator_name",
     *         test_case_public_id: "test_case_public_id",
     *         scoring_config_type: "scoring_config_type",
     *         is_assigned: true,
     *         is_sample: true,
     *         rejected: true,
     *         exclude_assigned_to_annotators: true
     *     })
     */
    public getTestcasesApi(
        request: Api.GetTestcasesApiTestcasesGetRequest = {},
        requestOptions?: Testcases.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getTestcasesApi(request, requestOptions));
    }

    private async __getTestcasesApi(
        request: Api.GetTestcasesApiTestcasesGetRequest = {},
        requestOptions?: Testcases.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const {
            start_path: startPath,
            test_case_set_ids: testCaseSetIds,
            name,
            prompt,
            mode,
            page,
            page_size: pageSize,
            simulator_id: simulatorId,
            simulator_name: simulatorName,
            test_case_public_id: testCasePublicId,
            scoring_config_type: scoringConfigType,
            is_assigned: isAssigned,
            is_sample: isSample,
            rejected,
            exclude_assigned_to_annotators: excludeAssignedToAnnotators,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (startPath != null) {
            _queryParams.start_path = startPath;
        }

        if (testCaseSetIds != null) {
            _queryParams.test_case_set_ids = testCaseSetIds;
        }

        if (name != null) {
            _queryParams.name = name;
        }

        if (prompt != null) {
            _queryParams.prompt = prompt;
        }

        if (mode != null) {
            _queryParams.mode = mode;
        }

        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (simulatorId != null) {
            _queryParams.simulator_id = simulatorId.toString();
        }

        if (simulatorName != null) {
            _queryParams.simulator_name = simulatorName;
        }

        if (testCasePublicId != null) {
            _queryParams.test_case_public_id = testCasePublicId;
        }

        if (scoringConfigType != null) {
            _queryParams.scoring_config_type = scoringConfigType;
        }

        if (isAssigned != null) {
            _queryParams.is_assigned = isAssigned.toString();
        }

        if (isSample != null) {
            _queryParams.is_sample = isSample.toString();
        }

        if (rejected != null) {
            _queryParams.rejected = rejected.toString();
        }

        if (excludeAssignedToAnnotators != null) {
            _queryParams.exclude_assigned_to_annotators = excludeAssignedToAnnotators.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "testcases",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError("Timeout exceeded when calling GET /testcases.");
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Api-Key": apiKeyValue };
    }
}
