// This file was auto-generated by Fern from our API Definition.

export interface BaseStructuredRunLog {
    source?: BaseStructuredRunLog.Source;
    type?: BaseStructuredRunLog.Type;
    timestamp?: string;
}

export namespace BaseStructuredRunLog {
    export const Source = {
        System: "system",
        Agent: "agent",
        Simulator: "simulator",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
    export const Type = {
        Proxy: "proxy",
        DockerApp: "docker_app",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
