// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../index.js";

export interface BatchLogRequest {
    source: string;
    type: string;
    timestamp: string;
    session_id: string;
    mutations: Api.BaseStructuredRunLog[];
    count: number;
}
