// This file was auto-generated by Fern from our API Definition.

export interface ChromeCookie {
    name: string;
    value: string;
    domain: string;
    path: string;
    expires: number;
    httpOnly: boolean;
    secure: boolean;
}
