// This file was auto-generated by Fern from our API Definition.

/**
 * Request to create a VM snapshot with optional labeling.
 */
export interface CreateSnapshotRequest {
    service?: string;
    git_hash?: string;
    dataset?: string;
    notes?: string;
    flows?: string;
    plato_config?: string;
    internal_app_port?: number;
    messaging_port?: number;
}
