// This file was auto-generated by Fern from our API Definition.

/**
 * Database configuration from plato config
 */
export interface DbConfigResponse {
    db_type: string;
    db_port: number;
    db_user: string;
    db_password: string;
    db_database: string;
}
