// This file was auto-generated by Fern from our API Definition.

import type * as Api from "../index.js";

export interface ResetEnvTask {
    prompt: string;
    start_url?: string;
    name: string;
    dataset_name?: string;
    eval_config?: Api.BaseScoringConfig;
}
