// This file was auto-generated by Fern from our API Definition.

/**
 * Base class for mutation listener configurations.
 */
export interface SimConfigListener {
    /** Listener type */
    type: SimConfigListener.Type;
}

export namespace SimConfigListener {
    export const Type = {
        Proxy: "proxy",
        DockerApp: "docker_app",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
