// This file was auto-generated by Fern from our API Definition.

/**
 * Compute resource configuration for a simulator.
 */
export interface SimConfigCompute {
    /** vCPUs */
    cpus?: number;
    /** Memory in MB */
    memory?: number;
    /** Disk space in MB */
    disk?: number;
    /** Application port */
    app_port?: number;
    /** Plato messaging port */
    plato_messaging_port?: number;
}
