// This file was auto-generated by Fern from our API Definition.

export interface SimulatorVersionDetails {
    artifact_id: string;
    version: string;
    created_at: string;
    worker_image: string;
    ecs_task_definition_arn: string;
    snapshot_s3_uri: string;
    dataset: string;
}
