// This file was auto-generated by Fern from our API Definition.

export interface VmManagementResponse {
    /** Status */
    status: string;
    /** Timestamp */
    timestamp?: string;
    /** Correlation ID for tracking */
    correlation_id: string;
}
