// This file was auto-generated by Fern from our API Definition.

/**
 * Response model for worker ready endpoint.
 */
export interface WorkerReadyResponse {
    ready: boolean;
    job_id?: string;
    worker_private_ip?: string;
    worker_public_ip?: string;
    mesh_ip?: string;
    worker_port?: number;
    health_status?: Record<string, unknown>;
    error?: string;
}
