# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .active_session_response import ActiveSessionResponse
    from .backup_environment_response import BackupEnvironmentResponse
    from .cdp_url_response import CdpUrlResponse
    from .cdp_url_response_data import CdpUrlResponseData
    from .close_environment_response import CloseEnvironmentResponse
    from .create_sandbox_response import CreateSandboxResponse
    from .create_snapshot_response import CreateSnapshotResponse
    from .delete_sandbox_response import DeleteSandboxResponse
    from .environment import Environment
    from .environment_state_response import EnvironmentStateResponse
    from .environment_state_response_data import EnvironmentStateResponseData
    from .error_response import ErrorResponse
    from .evaluate_response import EvaluateResponse
    from .evaluate_response_score import EvaluateResponseScore
    from .evaluate_response_score_result import EvaluateResponseScoreResult
    from .evaluation_result import EvaluationResult
    from .heartbeat_response import HeartbeatResponse
    from .job_status_response import JobStatusResponse
    from .log_response import LogResponse
    from .make_environment_response import MakeEnvironmentResponse
    from .operation_event import OperationEvent
    from .operation_event_type import OperationEventType
    from .plato_config import PlatoConfig
    from .plato_task import PlatoTask
    from .plato_task_metadata import PlatoTaskMetadata
    from .plato_task_metadata_reasoning_level import PlatoTaskMetadataReasoningLevel
    from .post_evaluation_result_response import PostEvaluationResultResponse
    from .proxy_url_response import ProxyUrlResponse
    from .proxy_url_response_data import ProxyUrlResponseData
    from .reset_environment_response import ResetEnvironmentResponse
    from .reset_environment_response_data import ResetEnvironmentResponseData
    from .running_sessions_count_response import RunningSessionsCountResponse
    from .sandbox import Sandbox
    from .scoring_type import ScoringType
    from .setup_root_access_response import SetupRootAccessResponse
    from .setup_sandbox_response import SetupSandboxResponse
    from .sim_config_compute import SimConfigCompute
    from .sim_config_dataset import SimConfigDataset
    from .sim_config_listener import SimConfigListener
    from .sim_config_listener_type import SimConfigListenerType
    from .sim_config_metadata import SimConfigMetadata
    from .sim_config_service import SimConfigService
    from .simulator import Simulator
    from .simulator_list_item import SimulatorListItem
    from .ssh_info import SshInfo
    from .start_worker_response import StartWorkerResponse
    from .task_metadata import TaskMetadata
    from .task_metadata_reasoning_level import TaskMetadataReasoningLevel
    from .test_case import TestCase
    from .test_case_default_scoring_config import TestCaseDefaultScoringConfig
    from .test_case_scoring_types_item import TestCaseScoringTypesItem
    from .test_case_simulator import TestCaseSimulator
    from .test_cases_response import TestCasesResponse
    from .variable import Variable
    from .worker_ready_response import WorkerReadyResponse
_dynamic_imports: typing.Dict[str, str] = {
    "ActiveSessionResponse": ".active_session_response",
    "BackupEnvironmentResponse": ".backup_environment_response",
    "CdpUrlResponse": ".cdp_url_response",
    "CdpUrlResponseData": ".cdp_url_response_data",
    "CloseEnvironmentResponse": ".close_environment_response",
    "CreateSandboxResponse": ".create_sandbox_response",
    "CreateSnapshotResponse": ".create_snapshot_response",
    "DeleteSandboxResponse": ".delete_sandbox_response",
    "Environment": ".environment",
    "EnvironmentStateResponse": ".environment_state_response",
    "EnvironmentStateResponseData": ".environment_state_response_data",
    "ErrorResponse": ".error_response",
    "EvaluateResponse": ".evaluate_response",
    "EvaluateResponseScore": ".evaluate_response_score",
    "EvaluateResponseScoreResult": ".evaluate_response_score_result",
    "EvaluationResult": ".evaluation_result",
    "HeartbeatResponse": ".heartbeat_response",
    "JobStatusResponse": ".job_status_response",
    "LogResponse": ".log_response",
    "MakeEnvironmentResponse": ".make_environment_response",
    "OperationEvent": ".operation_event",
    "OperationEventType": ".operation_event_type",
    "PlatoConfig": ".plato_config",
    "PlatoTask": ".plato_task",
    "PlatoTaskMetadata": ".plato_task_metadata",
    "PlatoTaskMetadataReasoningLevel": ".plato_task_metadata_reasoning_level",
    "PostEvaluationResultResponse": ".post_evaluation_result_response",
    "ProxyUrlResponse": ".proxy_url_response",
    "ProxyUrlResponseData": ".proxy_url_response_data",
    "ResetEnvironmentResponse": ".reset_environment_response",
    "ResetEnvironmentResponseData": ".reset_environment_response_data",
    "RunningSessionsCountResponse": ".running_sessions_count_response",
    "Sandbox": ".sandbox",
    "ScoringType": ".scoring_type",
    "SetupRootAccessResponse": ".setup_root_access_response",
    "SetupSandboxResponse": ".setup_sandbox_response",
    "SimConfigCompute": ".sim_config_compute",
    "SimConfigDataset": ".sim_config_dataset",
    "SimConfigListener": ".sim_config_listener",
    "SimConfigListenerType": ".sim_config_listener_type",
    "SimConfigMetadata": ".sim_config_metadata",
    "SimConfigService": ".sim_config_service",
    "Simulator": ".simulator",
    "SimulatorListItem": ".simulator_list_item",
    "SshInfo": ".ssh_info",
    "StartWorkerResponse": ".start_worker_response",
    "TaskMetadata": ".task_metadata",
    "TaskMetadataReasoningLevel": ".task_metadata_reasoning_level",
    "TestCase": ".test_case",
    "TestCaseDefaultScoringConfig": ".test_case_default_scoring_config",
    "TestCaseScoringTypesItem": ".test_case_scoring_types_item",
    "TestCaseSimulator": ".test_case_simulator",
    "TestCasesResponse": ".test_cases_response",
    "Variable": ".variable",
    "WorkerReadyResponse": ".worker_ready_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActiveSessionResponse",
    "BackupEnvironmentResponse",
    "CdpUrlResponse",
    "CdpUrlResponseData",
    "CloseEnvironmentResponse",
    "CreateSandboxResponse",
    "CreateSnapshotResponse",
    "DeleteSandboxResponse",
    "Environment",
    "EnvironmentStateResponse",
    "EnvironmentStateResponseData",
    "ErrorResponse",
    "EvaluateResponse",
    "EvaluateResponseScore",
    "EvaluateResponseScoreResult",
    "EvaluationResult",
    "HeartbeatResponse",
    "JobStatusResponse",
    "LogResponse",
    "MakeEnvironmentResponse",
    "OperationEvent",
    "OperationEventType",
    "PlatoConfig",
    "PlatoTask",
    "PlatoTaskMetadata",
    "PlatoTaskMetadataReasoningLevel",
    "PostEvaluationResultResponse",
    "ProxyUrlResponse",
    "ProxyUrlResponseData",
    "ResetEnvironmentResponse",
    "ResetEnvironmentResponseData",
    "RunningSessionsCountResponse",
    "Sandbox",
    "ScoringType",
    "SetupRootAccessResponse",
    "SetupSandboxResponse",
    "SimConfigCompute",
    "SimConfigDataset",
    "SimConfigListener",
    "SimConfigListenerType",
    "SimConfigMetadata",
    "SimConfigService",
    "Simulator",
    "SimulatorListItem",
    "SshInfo",
    "StartWorkerResponse",
    "TaskMetadata",
    "TaskMetadataReasoningLevel",
    "TestCase",
    "TestCaseDefaultScoringConfig",
    "TestCaseScoringTypesItem",
    "TestCaseSimulator",
    "TestCasesResponse",
    "Variable",
    "WorkerReadyResponse",
]
