# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateSandboxResponse(UniversalBaseModel):
    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public URL for the sandbox
    """

    job_public_id: str = pydantic.Field()
    """
    Public ID of the sandbox job
    """

    job_group_id: str = pydantic.Field()
    """
    Job group ID for the sandbox
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current status of the sandbox
    """

    correlation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Correlation ID for monitoring operation progress via SSE
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
