# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .operation_event_type import OperationEventType


class OperationEvent(UniversalBaseModel):
    """
    Server-sent event for operation monitoring. The SSE data field contains base64-encoded JSON of this object.

    **Event Types:**
    - `connected`: Initial connection event, no action needed, continue listening
    - `progress`: Progress update with human-readable message
    - `run_result`: Sandbox setup/creation completed (check `success` field)
    - `ssh_result`: SSH setup operation completed (check `success` field)
    - `error`: Operation failed (check `error` or `message` field)

    **Terminal Events:**
    `run_result`, `ssh_result`, and `error` are terminal events that indicate the operation has finished.
    Close the stream after receiving one of these.

    **Success Detection:**
    An operation is successful if you receive `run_result` or `ssh_result` with `success: true`.
    An operation failed if you receive an `error` event or a result event with `success: false`.
    """

    type: OperationEventType = pydantic.Field()
    """
    Type of operation event
    """

    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the operation was successful (only present in result events)
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if operation failed
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable progress or status message
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
