# This file was auto-generated by Fern from our API Definition.

import typing

OperationEventType = typing.Union[
    typing.Literal["connected", "run_result", "ssh_result", "error", "progress"], typing.Any
]
