# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .plato_task_metadata import PlatoTaskMetadata
from .scoring_type import ScoringType


class PlatoTask(UniversalBaseModel):
    public_id: str
    name: str
    prompt: str
    env_id: str
    start_url: str
    dataset_name: typing.Optional[str] = None
    average_time: typing.Optional[float] = None
    average_steps: typing.Optional[int] = None
    num_validator_human_scores: typing.Optional[int] = None
    default_scoring_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    scoring_type: typing.Optional[typing.List[ScoringType]] = None
    output_schema: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    is_sample: typing.Optional[bool] = None
    simulator_artifact_id: typing.Optional[str] = None
    metadata: typing.Optional[PlatoTaskMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
