# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .variable import Variable


class SimConfigMetadata(UniversalBaseModel):
    favicon: typing.Optional[str] = None
    name: str
    description: typing.Optional[str] = None
    source_code_url: typing.Optional[str] = None
    start_url: typing.Optional[str] = None
    license: typing.Optional[str] = None
    variables: typing.Optional[typing.List[Variable]] = None
    flows_path: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
