# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .task_metadata import TaskMetadata
from .test_case_default_scoring_config import TestCaseDefaultScoringConfig
from .test_case_scoring_types_item import TestCaseScoringTypesItem
from .test_case_simulator import TestCaseSimulator


class TestCase(UniversalBaseModel):
    public_id: typing_extensions.Annotated[str, FieldMetadata(alias="publicId")]
    name: str
    prompt: str
    start_url: typing_extensions.Annotated[str, FieldMetadata(alias="startUrl")]
    simulator: TestCaseSimulator
    average_time_taken: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="averageTimeTaken")] = (
        None
    )
    average_steps_taken: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="averageStepsTaken")] = (
        None
    )
    default_scoring_config: typing_extensions.Annotated[
        typing.Optional[TestCaseDefaultScoringConfig], FieldMetadata(alias="defaultScoringConfig")
    ] = None
    scoring_types: typing_extensions.Annotated[
        typing.Optional[typing.List[TestCaseScoringTypesItem]], FieldMetadata(alias="scoringTypes")
    ] = None
    output_schema: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]], FieldMetadata(alias="outputSchema")
    ] = None
    is_sample: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="isSample")] = None
    simulator_artifact_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="simulatorArtifactId")
    ] = None
    metadata_config: typing_extensions.Annotated[
        typing.Optional[TaskMetadata], FieldMetadata(alias="metadataConfig")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
