# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WorkerReadyResponse(UniversalBaseModel):
    ready: bool
    worker_ip: typing.Optional[str] = None
    worker_port: typing.Optional[int] = None
    health_status: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    error: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
