// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Api from "../../../index.js";

export declare namespace PublicBuild {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PublicBuild {
    protected readonly _options: PublicBuild.Options;

    constructor(_options: PublicBuild.Options) {
        this._options = _options;
    }

    /**
     * Stream operation results via Server-Sent Events (SSE) for public usage.
     *
     * Returns a stream of events with the following format:
     * - event: Event type (e.g., "connected", "progress", "complete", "error")
     * - data: JSON payload with event details
     *
     * Events:
     * - connected: Initial connection established
     * - progress: Operation progress update
     * - complete: Operation completed successfully
     * - error: Operation failed with error details
     *
     * @param {string} correlation_id
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.getOperationEventsApi("correlation_id")
     */
    public getOperationEventsApi(
        correlation_id: string,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__getOperationEventsApi(correlation_id, requestOptions));
    }

    private async __getOperationEventsApi(
        correlation_id: string,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `public-build/events/${core.url.encodePathParam(correlation_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling GET /public-build/events/{correlation_id}.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Api.CreateVmRequest} request
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.createVmApi({
     *         dataset: "dataset",
     *         plato_dataset_config: {
     *             compute: {},
     *             metadata: {}
     *         }
     *     })
     */
    public createVmApi(
        request: Api.CreateVmRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<Api.CreateVmResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createVmApi(request, requestOptions));
    }

    private async __createVmApi(
        request: Api.CreateVmRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<Api.CreateVmResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "public-build/vm/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.CreateVmResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError("Timeout exceeded when calling POST /public-build/vm/create.");
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Close and terminate a VM.
     *
     * @param {string} public_id
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.closeVmApi("public_id")
     */
    public closeVmApi(
        public_id: string,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<Api.VmManagementResponse> {
        return core.HttpResponsePromise.fromPromise(this.__closeVmApi(public_id, requestOptions));
    }

    private async __closeVmApi(
        public_id: string,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<Api.VmManagementResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `public-build/vm/${core.url.encodePathParam(public_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.VmManagementResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError("Timeout exceeded when calling DELETE /public-build/vm/{public_id}.");
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a checkpoint snapshot of a VM.
     *
     * This creates a blockdiff_checkpoint artifact type instead of a regular blockdiff.
     * Optional parameters allow overriding artifact labels:
     * - service: Simulator name (defaults to job's service)
     * - git_hash: Git hash/version (defaults to job's version or "unknown")
     * - dataset: Dataset name (defaults to job's dataset)
     *
     * @param {string} public_id
     * @param {Api.CreateSnapshotRequest} request
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.checkpointVmApi("public_id")
     */
    public checkpointVmApi(
        public_id: string,
        request?: Api.CreateSnapshotRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<Api.CreateSnapshotResponse> {
        return core.HttpResponsePromise.fromPromise(this.__checkpointVmApi(public_id, request, requestOptions));
    }

    private async __checkpointVmApi(
        public_id: string,
        request?: Api.CreateSnapshotRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<Api.CreateSnapshotResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `public-build/vm/${core.url.encodePathParam(public_id)}/checkpoint`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request != null ? request : undefined,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.CreateSnapshotResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling POST /public-build/vm/{public_id}/checkpoint.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Setup SSH key-based authentication for the root user.
     *
     * @param {string} public_id
     * @param {Api.SetupRootPasswordRequest} request
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.setupRootAccessApi("public_id", {
     *         ssh_public_key: "ssh_public_key"
     *     })
     */
    public setupRootAccessApi(
        public_id: string,
        request: Api.SetupRootPasswordRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<Api.VmManagementResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setupRootAccessApi(public_id, request, requestOptions));
    }

    private async __setupRootAccessApi(
        public_id: string,
        request: Api.SetupRootPasswordRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<Api.VmManagementResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `public-build/vm/${core.url.encodePathParam(public_id)}/setup-root-access`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.VmManagementResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling POST /public-build/vm/{public_id}/setup-root-access.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Setup sandbox development environment with git clone.
     *
     * @param {string} public_id
     * @param {Api.SetupSandboxRequest} request
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.setupSandboxApi("public_id", {
     *         dataset: "dataset",
     *         plato_dataset_config: {
     *             compute: {},
     *             metadata: {}
     *         }
     *     })
     */
    public setupSandboxApi(
        public_id: string,
        request: Api.SetupSandboxRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<Api.SetupSandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setupSandboxApi(public_id, request, requestOptions));
    }

    private async __setupSandboxApi(
        public_id: string,
        request: Api.SetupSandboxRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<Api.SetupSandboxResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `public-build/vm/${core.url.encodePathParam(public_id)}/setup-sandbox`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.SetupSandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling POST /public-build/vm/{public_id}/setup-sandbox.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Save a snapshot of a VM.
     *
     * Optional parameters allow overriding artifact labels:
     * - service: Simulator name (defaults to job's service)
     * - git_hash: Git hash/version (defaults to job's version or "unknown")
     * - dataset: Dataset name (defaults to job's dataset)
     *
     * @param {string} public_id
     * @param {Api.CreateSnapshotRequest} request
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.saveVmSnapshotApi("public_id")
     */
    public saveVmSnapshotApi(
        public_id: string,
        request?: Api.CreateSnapshotRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<Api.CreateSnapshotResponse> {
        return core.HttpResponsePromise.fromPromise(this.__saveVmSnapshotApi(public_id, request, requestOptions));
    }

    private async __saveVmSnapshotApi(
        public_id: string,
        request?: Api.CreateSnapshotRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<Api.CreateSnapshotResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `public-build/vm/${core.url.encodePathParam(public_id)}/snapshot`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request != null ? request : undefined,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.CreateSnapshotResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling POST /public-build/vm/{public_id}/snapshot.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Start listeners: write env.py and worker compose from dataset config, then restart worker.
     *
     * @param {string} public_id
     * @param {Api.VmManagementRequest} request
     * @param {PublicBuild.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.publicBuild.startWorkerApi("public_id", {
     *         dataset: "dataset",
     *         plato_dataset_config: {
     *             compute: {},
     *             metadata: {}
     *         }
     *     })
     */
    public startWorkerApi(
        public_id: string,
        request: Api.VmManagementRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): core.HttpResponsePromise<Api.VmManagementResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startWorkerApi(public_id, request, requestOptions));
    }

    private async __startWorkerApi(
        public_id: string,
        request: Api.VmManagementRequest,
        requestOptions?: PublicBuild.RequestOptions,
    ): Promise<core.WithRawResponse<Api.VmManagementResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `public-build/vm/${core.url.encodePathParam(public_id)}/start-worker`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.VmManagementResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling POST /public-build/vm/{public_id}/start-worker.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Api-Key": apiKeyValue };
    }
}
