// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Api from "../../../index.js";

export declare namespace Gitea {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Gitea {
    protected readonly _options: Gitea.Options;

    constructor(_options: Gitea.Options) {
        this._options = _options;
    }

    /**
     * Get Gitea credentials for the organization
     *
     * @param {Api.GetGiteaCredentialsRequest} request
     * @param {Gitea.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.gitea.getGiteaCredentials({
     *         authorization: "authorization",
     *         "X-Internal-Service": "X-Internal-Service"
     *     })
     */
    public getGiteaCredentials(
        request: Api.GetGiteaCredentialsRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): core.HttpResponsePromise<Api.GiteaCredentialsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getGiteaCredentials(request, requestOptions));
    }

    private async __getGiteaCredentials(
        request: Api.GetGiteaCredentialsRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): Promise<core.WithRawResponse<Api.GiteaCredentialsResponse>> {
        const { authorization, "X-Internal-Service": internalService } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                authorization: authorization != null ? authorization : undefined,
                "X-Internal-Service": internalService != null ? internalService : undefined,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "gitea/credentials",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.GiteaCredentialsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError("Timeout exceeded when calling GET /gitea/credentials.");
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get the current user's Gitea info (auto-provisions if needed)
     *
     * @param {Api.GetMyGiteaInfoRequest} request
     * @param {Gitea.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.gitea.getMyGiteaInfo({
     *         authorization: "authorization",
     *         "X-Internal-Service": "X-Internal-Service"
     *     })
     */
    public getMyGiteaInfo(
        request: Api.GetMyGiteaInfoRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): core.HttpResponsePromise<Api.GiteaInfoResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getMyGiteaInfo(request, requestOptions));
    }

    private async __getMyGiteaInfo(
        request: Api.GetMyGiteaInfoRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): Promise<core.WithRawResponse<Api.GiteaInfoResponse>> {
        const { authorization, "X-Internal-Service": internalService } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                authorization: authorization != null ? authorization : undefined,
                "X-Internal-Service": internalService != null ? internalService : undefined,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "gitea/my-info",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.GiteaInfoResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError("Timeout exceeded when calling GET /gitea/my-info.");
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get simulators that user has access to view repos for
     *
     * @param {Api.GetAccessibleSimulatorsRequest} request
     * @param {Gitea.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.gitea.getAccessibleSimulators({
     *         authorization: "authorization",
     *         "X-Internal-Service": "X-Internal-Service"
     *     })
     */
    public getAccessibleSimulators(
        request: Api.GetAccessibleSimulatorsRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): core.HttpResponsePromise<Api.AppSchemasGiteaResponsesSimulatorListItemResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__getAccessibleSimulators(request, requestOptions));
    }

    private async __getAccessibleSimulators(
        request: Api.GetAccessibleSimulatorsRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): Promise<core.WithRawResponse<Api.AppSchemasGiteaResponsesSimulatorListItemResponse[]>> {
        const { authorization, "X-Internal-Service": internalService } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                authorization: authorization != null ? authorization : undefined,
                "X-Internal-Service": internalService != null ? internalService : undefined,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "gitea/simulators",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Api.AppSchemasGiteaResponsesSimulatorListItemResponse[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError("Timeout exceeded when calling GET /gitea/simulators.");
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get repository details for a specific simulator
     *
     * @param {number} simulator_id
     * @param {Api.GetSimulatorRepositoryRequest} request
     * @param {Gitea.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.gitea.getSimulatorRepository(1, {
     *         authorization: "authorization",
     *         "X-Internal-Service": "X-Internal-Service"
     *     })
     */
    public getSimulatorRepository(
        simulator_id: number,
        request: Api.GetSimulatorRepositoryRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): core.HttpResponsePromise<Api.SimulatorRepositoryResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getSimulatorRepository(simulator_id, request, requestOptions),
        );
    }

    private async __getSimulatorRepository(
        simulator_id: number,
        request: Api.GetSimulatorRepositoryRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): Promise<core.WithRawResponse<Api.SimulatorRepositoryResponse>> {
        const { authorization, "X-Internal-Service": internalService } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                authorization: authorization != null ? authorization : undefined,
                "X-Internal-Service": internalService != null ? internalService : undefined,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `gitea/simulators/${core.url.encodePathParam(simulator_id)}/repo`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.SimulatorRepositoryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling GET /gitea/simulators/{simulator_id}/repo.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a repository for a simulator (only if it doesn't exist)
     *
     * @param {number} simulator_id
     * @param {Api.CreateSimulatorRepositoryRequest} request
     * @param {Gitea.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.gitea.createSimulatorRepository(1, {
     *         authorization: "authorization",
     *         "X-Internal-Service": "X-Internal-Service"
     *     })
     */
    public createSimulatorRepository(
        simulator_id: number,
        request: Api.CreateSimulatorRepositoryRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): core.HttpResponsePromise<Api.RepositoryResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__createSimulatorRepository(simulator_id, request, requestOptions),
        );
    }

    private async __createSimulatorRepository(
        simulator_id: number,
        request: Api.CreateSimulatorRepositoryRequest = {},
        requestOptions?: Gitea.RequestOptions,
    ): Promise<core.WithRawResponse<Api.RepositoryResponse>> {
        const { authorization, "X-Internal-Service": internalService } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                authorization: authorization != null ? authorization : undefined,
                "X-Internal-Service": internalService != null ? internalService : undefined,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `gitea/simulators/${core.url.encodePathParam(simulator_id)}/repo`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Api.RepositoryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling POST /gitea/simulators/{simulator_id}/repo.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Api-Key": apiKeyValue };
    }
}
