// Code generated by Fern. DO NOT EDIT.

package root_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	sdk "sdk"
	client "sdk/client"
	option "sdk/option"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestMakeEnvironmentWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.MakeEnvironmentRequest{
		InterfaceType: "interface_type",
		EnvId:         "env_id",
	}
	_, invocationErr := client.MakeEnvironment(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/make2", nil, 1)
}

func TestGetJobStatusWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.GetJobStatus(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/env/job_id/status", nil, 1)
}

func TestGetCdpUrlWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.GetCdpUrl(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/env/job_id/cdp_url", nil, 1)
}

func TestGetProxyUrlWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.GetProxyUrl(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/env/job_id/proxy_url", nil, 1)
}

func TestCloseEnvironmentWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.CloseEnvironment(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/job_id/close", nil, 1)
}

func TestBackupEnvironmentWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.BackupEnvironment(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/job_id/backup", nil, 1)
}

func TestResetEnvironmentWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.ResetEnvironmentRequest{}
	_, invocationErr := client.ResetEnvironment(
		context.TODO(),
		"job_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/job_id/reset", nil, 1)
}

func TestGetEnvironmentStateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.GetEnvironmentStateRequest{
		MergeMutations: sdk.Bool(
			true,
		),
	}
	_, invocationErr := client.GetEnvironmentState(
		context.TODO(),
		"job_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/env/job_id/state", map[string]string{"merge_mutations": "true"}, 1)
}

func TestGetWorkerReadyWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.GetWorkerReady(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/env/job_id/worker_ready", nil, 1)
}

func TestSendHeartbeatWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.SendHeartbeat(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/job_id/heartbeat", nil, 1)
}

func TestGetActiveSessionWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.GetActiveSession(
		context.TODO(),
		"job_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/env/job_id/active_session", nil, 1)
}

func TestEvaluateSessionWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.EvaluateRequest{}
	_, invocationErr := client.EvaluateSession(
		context.TODO(),
		"session_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/session/session_id/evaluate", nil, 1)
}

func TestPostEvaluationResultWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.PostEvaluationResultRequest{
		Success: true,
	}
	_, invocationErr := client.PostEvaluationResult(
		context.TODO(),
		"session_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/session/session_id/score", nil, 1)
}

func TestLogMessageWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.LogRequest{
		Source: "source",
		Type:   "type",
		Message: map[string]any{
			"key": "value",
		},
		Timestamp: "timestamp",
	}
	_, invocationErr := client.LogMessage(
		context.TODO(),
		"session_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/env/session_id/log", nil, 1)
}

func TestListSimulatorsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.ListSimulators(
		context.TODO(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/env/simulators", nil, 1)
}

func TestGetTestCasesWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.GetTestCasesRequest{
		SimulatorName: sdk.String(
			"simulator_name",
		),
		SimulatorId: sdk.String(
			"simulator_id",
		),
		PageSize: sdk.Int(
			1,
		),
	}
	_, invocationErr := client.GetTestCases(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/testcases", map[string]string{"simulator_name": "simulator_name", "simulator_id": "simulator_id", "page_size": "1"}, 1)
}

func TestGetRunningSessionsCountWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.GetRunningSessionsCount(
		context.TODO(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/user/organization/running-sessions", nil, 1)
}

func TestMonitorOperationWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.MonitorOperation(
		context.TODO(),
		"correlation_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/public-build/events/correlation_id", nil, 1)
}

func TestCreateSandboxWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.CreateSandboxRequest{
		Dataset: "dataset",
		PlatoDatasetConfig: &sdk.SimConfigDataset{
			Compute: &sdk.SimConfigCompute{
				Cpus:               1,
				Memory:             1,
				Disk:               1,
				AppPort:            1,
				PlatoMessagingPort: 1,
			},
			Metadata: &sdk.SimConfigMetadata{
				Name: "name",
			},
		},
	}
	_, invocationErr := client.CreateSandbox(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/public-build/vm/create", nil, 1)
}

func TestSetupSandboxWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.SetupSandboxRequest{
		Dataset: "dataset",
		PlatoDatasetConfig: &sdk.SimConfigDataset{
			Compute: &sdk.SimConfigCompute{
				Cpus:               1,
				Memory:             1,
				Disk:               1,
				AppPort:            1,
				PlatoMessagingPort: 1,
			},
			Metadata: &sdk.SimConfigMetadata{
				Name: "name",
			},
		},
	}
	_, invocationErr := client.SetupSandbox(
		context.TODO(),
		"job_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/public-build/vm/job_id/setup-sandbox", nil, 1)
}

func TestDeleteSandboxWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.DeleteSandbox(
		context.TODO(),
		"public_id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/public-build/vm/public_id", nil, 1)
}

func TestCreateSnapshotWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.CreateSnapshotRequest{}
	_, invocationErr := client.CreateSnapshot(
		context.TODO(),
		"public_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/public-build/vm/public_id/snapshot", nil, 1)
}

func TestStartWorkerWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.StartWorkerRequest{
		Dataset: "dataset",
		PlatoDatasetConfig: &sdk.SimConfigDataset{
			Compute: &sdk.SimConfigCompute{
				Cpus:               1,
				Memory:             1,
				Disk:               1,
				AppPort:            1,
				PlatoMessagingPort: 1,
			},
			Metadata: &sdk.SimConfigMetadata{
				Name: "name",
			},
		},
	}
	_, invocationErr := client.StartWorker(
		context.TODO(),
		"public_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/public-build/vm/public_id/start-worker", nil, 1)
}

func TestSetupRootAccessWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &sdk.SetupRootAccessRequest{
		SshPublicKey: "ssh_public_key",
	}
	_, invocationErr := client.SetupRootAccess(
		context.TODO(),
		"public_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/public-build/vm/public_id/setup-root-access", nil, 1)
}
