// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Api from "../../../index.js";

export declare namespace User {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class User {
    protected readonly _options: User.Options;

    constructor(_options: User.Options) {
        this._options = _options;
    }

    /**
     * Get comprehensive session information for the user's organization.
     *
     * Args:
     *     last_n_hours: Number of hours to look back for peak calculation (default: 1)
     *
     * Returns:
     *     Dictionary containing:
     *     - running_sessions: Count of currently running sessions
     *     - pending_sessions: Count of sessions that are not ended but have status != RUN_STARTED
     *     - peak_running_count: Peak number of running sessions within the past last_n_hours period
     *
     * @param {Api.GetOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRequest} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.UnprocessableEntityError}
     *
     * @example
     *     await client.user.getOrganizationRunningSessionsEndpointApi({
     *         last_n_hours: 1
     *     })
     */
    public getOrganizationRunningSessionsEndpointApi(
        request: Api.GetOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRequest = {},
        requestOptions?: User.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(
            this.__getOrganizationRunningSessionsEndpointApi(request, requestOptions),
        );
    }

    private async __getOrganizationRunningSessionsEndpointApi(
        request: Api.GetOrganizationRunningSessionsEndpointApiUserOrganizationRunningSessionsGetRequest = {},
        requestOptions?: User.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { last_n_hours: lastNHours } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (lastNHours != null) {
            _queryParams.last_n_hours = lastNHours.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "user/organization/running-sessions",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Api.UnprocessableEntityError(
                        _response.error.body as Api.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApiTimeoutError(
                    "Timeout exceeded when calling GET /user/organization/running-sessions.",
                );
            case "unknown":
                throw new errors.ApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Api-Key": apiKeyValue };
    }
}
