name: Publish Dev Pre-release (TestPyPI)

on:
  push:
    branches: [main]

jobs:
  publish-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for OIDC trusted publishing

    env:
      # Change to your next intended minor/major base if you prefer (e.g., 2.0.0).
      # If omitted, we auto-read the current version in pyproject and append .dev...
      BASE_VERSION: "" # leave empty to auto-detect from pyproject

    defaults:
      run:
        working-directory: python

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build C bindings
        working-directory: .
        run: |
          ./scripts/build-python.sh
        shell: bash

      - name: Compute dev version & patch pyproject.toml
        id: version
        working-directory: .
        shell: python
        run: |
          import os, re, subprocess, datetime, pathlib, sys
          p = pathlib.Path("python/pyproject.toml")
          text = p.read_text(encoding="utf-8")

          # Grab current version from pyproject (PEP 621)
          m = re.search(r'(?m)^\s*version\s*=\s*"([^"]+)"\s*$', text)
          if not m:
            print("ERROR: Could not find version = \"...\" in pyproject.toml", file=sys.stderr)
            sys.exit(1)
          current = m.group(1)

          # Decide base version
          base = os.environ.get("BASE_VERSION") or current
          # Ensure base has no pre/local already
          base = base.split("+")[0]
          base = re.sub(r'(a|b|rc|dev).*$', "", base)

          # Build a unique dev version: <base>.devYYYYMMDDHHMMSS (PEP 440 compliant)
          now = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
          dev_version = f"{base}.dev{now}"

          patched = re.sub(r'(?m)^(\s*version\s*=\s*")([^"]+)(")',
                           r'\g<1>' + dev_version + r'\3', text)
          p.write_text(patched, encoding="utf-8")
          print(f"Patched version: {dev_version}")

          # Write to GITHUB_OUTPUT and GITHUB_ENV
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"dev_version={dev_version}\n")
          with open(os.environ["GITHUB_ENV"], "a") as f:
            f.write(f"DEV_VERSION={dev_version}\n")

          # Write to step summary
          with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as f:
            f.write(f"## 📦 Dev Package Published\n")
            f.write(f"- **Version:** `{dev_version}`\n")
            f.write(f"- **Base Version:** `{base}`\n")
            f.write(f"- **Timestamp:** {now}\n")
            f.write(f"- **Repository:** TestPyPI\n")
            f.write(f"\n### Install Command\n")
            f.write(f"```bash\n")
            f.write(f"pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ plato-sdk=={dev_version}\n")
            f.write(f"```\n")

      - name: Build sdist & wheel
        run: python -m build

      - name: Publish to TestPyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: python/dist/
          skip-existing: true
          verbose: true

      - name: Summary
        working-directory: .
        run: |
          echo "✅ Published to TestPyPI"
          echo ""
          echo "📦 Package: plato-sdk"
          echo "🏷️  Version: ${{ env.DEV_VERSION }}"
          echo "📍 URL: https://test.pypi.org/project/plato-sdk/${{ env.DEV_VERSION }}/"
          echo ""
          echo "Install with:"
          echo "  pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ plato-sdk==${{ env.DEV_VERSION }}"